Kumarev/update behaviors of stack resources
aws-samples/cfn101-workshop pull request #154
Opened 2022-02-25 15:41 UTC by kumarev

update behaviors of stack resources:

Workshop content for 'update behaviors of stack resources'

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-03-01 19:13 UTC, mrinaudo-aws requested changes
Thank you, @kumarev !  Please review/approve suggestions, and ask for another review!

2022-03-01 19:13 UTC, mrinaudo-aws commented on workshop/content/intermediate/operations/update-behaviors-of-stack-resources/_index.md
> +Save your changes to the `update-behaviors-of-stack-resources.yaml` template. Before you update the stack with your updated template, see [Update requires](https://docs.aws.amazon.com/AWSCloudFormati
```suggestion
Save your changes to the `update-behaviors-of-stack-resources.yaml` template. Before you update the stack with your updated template, see the **Update requires** [section](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance.html#cfn-ec2-instance-tags) for the `Tags` property; you will notice that **Update requires**, in this case, requires [No interruption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-no-interrupt).
```

2022-03-01 19:13 UTC, mrinaudo-aws commented on workshop/content/intermediate/operations/update-behaviors-of-stack-resources/_index.md
> +Congratulations! You now have now learned about the update behaviors of stack resources!
```suggestion
Congratulations! You now have now learned the update behaviors of stack resources!
```

2022-03-01 20:38 UTC, mrinaudo-aws approved these changes
lgtm

2022-03-03 10:12 UTC, rezabekf requested changes
Just a small rewording of introduction. Other than that LGMT. Once my comment gets resolved, I am ready to merge.

2022-03-03 13:15 UTC, kumarev commented
> Just a small rewording of introduction. Other than that LGMT. Once my comment gets resolved, I am ready to merge.

Done, applied the suggestions. Thanks!

2022-03-03 14:11 UTC, rezabekf approved these changes
Approved

2022-03-03 14:13 UTC, merged