modified index.md file
aws-samples/cfn101-workshop pull request #159
Opened 2022-03-03 00:37 UTC by dreddy-aws

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-03-09 17:32 UTC, mrinaudo-aws requested changes
@dreddy-aws thanks!  Please review/approve/update, and request another review!

2022-03-09 17:32 UTC, mrinaudo-aws commented on workshop/content/basics/templates/finding-output-values/_index.md
> +* Use `Ref` intrinsic function, and pass the logical ID of the Amazon EC2 instance resource to retrieve the instance ID; similarly, pass the logical ID of the Amazon EC2 instance resource along with
```suggestion
* Use `Ref` intrinsic function, and pass the logical ID of the Amazon EC2 instance resource to retrieve the instance ID; similarly, pass the logical ID of the Amazon EC2 instance resource, along with the `PublicIp` attribute to the `Fn::GetAtt` function, to retrieve the public IP of the instance.
```

2022-03-09 17:32 UTC, mrinaudo-aws commented on workshop/content/basics/templates/finding-output-values/_index.md
> +Great work! You have now learned how to find return values for a specified resource, and how to use them in your templates in other resources using `Ref`,  `Fn::GetAtt` and `Fn::Sub` [intrinsic funct
```suggestion
Great work! You have now learned how to find return values for a specified resource, and how to use them in your templates in other resources using `Ref`, `Fn::GetAtt`, and `Fn::Sub` [intrinsic functions](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference.html).
```

2022-03-09 17:32 UTC, mrinaudo-aws commented on code/solutions/resource-return-values/resource-return-values-challenge.yaml
> +Description: AWS CloudFormation workshop - Resource Dependencies Challenge Lab (uksb-1q9p31idr).
```suggestion
Description: AWS CloudFormation workshop - Resource Return Values Challenge Lab (uksb-1q9p31idr).
```

2022-03-09 17:32 UTC, mrinaudo-aws commented on code/solutions/resource-return-values/resource-return-values.yaml
> +Description: AWS CloudFormation workshop - Resource Return Values Lab with DependsOn attribute (uksb-1q9p31idr).
```suggestion
Description: AWS CloudFormation workshop - Resource Return Values Lab (uksb-1q9p31idr).
```

2022-03-09 17:32 UTC, mrinaudo-aws commented on code/workspace/resource-return-values/resource-return-values-challenge.yaml
> +Description: AWS CloudFormation workshop - Resource Dependencies Challenge Lab (uksb-1q9p31idr).
```suggestion
Description: AWS CloudFormation workshop - Resource Return Values Lab (uksb-1q9p31idr).
```

2022-03-09 17:32 UTC, mrinaudo-aws commented on code/workspace/resource-return-values/resource-return-values.yaml
> +Description: AWS CloudFormation workshop - Resource Return Values Lab with DependsOn attribute (uksb-1q9p31idr).
```suggestion
Description: AWS CloudFormation workshop - Resource Return Values Lab (uksb-1q9p31idr).
```

2022-03-09 17:32 UTC, mrinaudo-aws commented on workshop/content/basics/templates/finding-output-values/_index.md
> +        Version: 2012-10-17
```suggestion
        Version: "2012-10-17"
```

2022-03-09 17:32 UTC, mrinaudo-aws commented on workshop/content/basics/templates/finding-output-values/_index.md
> +              - 's3:*'
```suggestion
              - s3:*
```

2022-03-09 17:32 UTC, mrinaudo-aws commented on code/solutions/resource-return-values/resource-return-values-challenge.yaml
> +          Value: Resource-dependencies-workshop
```suggestion
          Value: Resource-return-values-workshop
```

2022-03-09 17:32 UTC, mrinaudo-aws commented on code/solutions/resource-return-values/resource-return-values-challenge.yaml
> +          Value: Resource-dependencies-workshop
```suggestion
          Value: Resource-return-values-workshop
```

2022-03-09 17:32 UTC, mrinaudo-aws commented on code/workspace/resource-return-values/resource-return-values-challenge.yaml
> +          Value: Resource-dependencies-workshop
```suggestion
          Value: Resource-return-values-workshop
```

2022-03-09 17:32 UTC, mrinaudo-aws commented on code/workspace/resource-return-values/resource-return-values-challenge.yaml
> +          Value: Resource-dependencies-workshop
```suggestion
          Value: Resource-return-values-workshop
```

2022-03-09 17:32 UTC, mrinaudo-aws commented on workshop/content/basics/templates/finding-output-values/_index.md
> +          Value: Resource-dependencies-workshop
```suggestion
          Value: Resource-return-values-workshop
```

2022-03-09 18:10 UTC, mrinaudo-aws approved these changes
lgtm

2022-03-09 18:16 UTC, mrinaudo-aws commented on workshop/content/basics/templates/finding-return-values/_index.md
> +---
@dreddy-aws can you actually rename the directory to `resource-return-values` for consistency with the code directories?  You might also need to change the image path in the markdown file.  Thanks!

2022-03-09 18:19 UTC, mrinaudo-aws submitted a review, later dismissed
lgtm

2022-03-10 13:41 UTC, rezabekf approved these changes
Approved.

2022-03-10 13:42 UTC, merged