Add Drift Detection workshop
aws-samples/cfn101-workshop pull request #162
Opened 2022-03-25 13:46 UTC by jamesoff

*Description of changes:*

Add Drift Detection workshop content.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-03-29 21:07 UTC, mrinaudo-aws requested changes
Thank you, @jamesoff !  Please review/approve suggestions, and request another review when ready!

2022-03-29 21:07 UTC, mrinaudo-aws commented on workshop/content/intermediate/operations/drift-detection/_index.md
> +3. Once the stack is updated, edit the template file again to remove the resource completely (you can comment it out, using the `#` character at the start of each line), and save the file.
```suggestion
3. Once the stack update is complete, edit the template file again to remove the whole resource declaration (you can also choose to comment it out, using the `#` character at the start of each relevant line), and save the file.
```

2022-03-31 20:23 UTC, mrinaudo-aws requested changes
Thank you, @jamesoff !  Can you please review/approve some more suggestions?  Thank you!

2022-03-31 20:23 UTC, mrinaudo-aws commented on workshop/content/intermediate/operations/drift-detection/_index.md
> +2. Choose the stack created in the first lab, for example `drift-detection-workshop`
```suggestion
2. Choose the stack created in the first lab, for example `drift-detection-workshop`.
```

2022-03-31 20:23 UTC, mrinaudo-aws commented on workshop/content/intermediate/operations/drift-detection/_index.md
> +3. Choose **Delete**, then choose the **Delete stack**
```suggestion
3. Choose **Delete**, then choose the **Delete stack**.
```

2022-03-31 20:23 UTC, mrinaudo-aws commented on workshop/content/intermediate/operations/drift-detection/_index.md
> +4. For the `drift-detection-challenge` stack, edit the template file to change the `DeletionPolicy` to `Delete`
```suggestion
4. For the `drift-detection-challenge` stack, edit the template file to change the `DeletionPolicy` to `Delete`.
```

2022-03-31 20:23 UTC, mrinaudo-aws commented on workshop/content/intermediate/operations/drift-detection/_index.md
> +$ echo "IyEvdXNyL2Jpbi9lbnYgYmFzaAplY2hvIEhlbGxvIFdvcmxkCg==" | base64 -d
```suggestion
$ echo "IyEvdXNyL2Jpbi9lbnYgYmFzaAplY2hvIEhlbGxvIFdvcmxkCg==" | base64 -d
```
```

2022-03-31 20:23 UTC, mrinaudo-aws commented on workshop/content/intermediate/operations/drift-detection/_index.md
> +
```suggestion

For example, when you run the following command:

```

2022-03-31 20:23 UTC, mrinaudo-aws commented on workshop/content/intermediate/operations/drift-detection/_index.md
> +#!/usr/bin/env bash
```suggestion

should display the following output:

```text
#!/usr/bin/env bash
```

2022-04-01 11:27 UTC, jamesoff commented
Suggestions applied and tested locally for correct display.

Force-pushed due to rewriting commit to fix author email (using the GitHub UI used my non-Amazon email).

2022-04-01 14:38 UTC, mrinaudo-aws approved these changes
lgtm

2022-04-05 10:36 UTC, rezabekf approved these changes
Approved

2022-04-05 10:37 UTC, merged