Translated workshop Intermediate section in Japanese v2
aws-samples/cfn101-workshop pull request #182
Opened 2022-11-16 11:14 UTC by rezabekf

*Issue #, if available:*
N/A
*Description of changes:*
This is v2 review for #179 which was merged before translators had a chance to review.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-12-12 05:06 UTC, ttymt commented
To cmick
I've pushed a new version of the template section.
Could you please review the template section first?

I haven't uploaded the operation section yet.

2023-01-05 07:55 UTC, cmick-aws commented
Starting review

2023-08-16 14:55 UTC, cmick-aws requested changes
Finished review.
@ttymt Please Check comments and fix as needed.

2023-08-16 14:55 UTC, cmick-aws commented on content/intermediate/templates/architecting-templates/index.ja.md
> +Cloud9 の `security-groups.template` ファイルを開きます。このサンプルテンプレートでは、2 つのセキュリティグループについて説明しています。1 つは作成するロードバランサー用、もう 1 つはサンプル Web アプリケーションを実行する EC2 インスタンス用です。どちらのセキュリティグループも、前に見たのと同じ方法で VPC ID を消費することに注意してくださ
「消費」→「利用」でどう？

2023-08-16 14:55 UTC, cmick-aws commented on content/intermediate/templates/architecting-templates/index.ja.md
> +Cloud9 の `security-groups.template` ファイルを開きます。このサンプルテンプレートでは、2 つのセキュリティグループについて説明しています。1 つは作成するロードバランサー用、もう 1 つはサンプル Web アプリケーションを実行する EC2 インスタンス用です。どちらのセキュリティグループも、前に見たのと同じ方法で VPC ID を消費することに注意してくださ
「Cloud9 の」→「Cloud9 で」でどう？
次のステップはそうなっている。

2023-08-16 14:55 UTC, cmick-aws commented on content/intermediate/templates/policy-as-code-with-guard/index.ja.md
>  Properties:
4.の中で、「両方のプロパティが期待どおりに説明されていること」の「説明」を「記述」でどう？

2023-08-16 14:55 UTC, cmick-aws commented on content/intermediate/templates/policy-as-code-with-guard/index.ja.md
> +[Amazon S3 バケット](https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket.html) の下に[プロパティ](https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/aw
Amazon S3 バケットの PublicAccessBlockConfiguration の全てのプロパティ true (Boolean) に設定します。

2023-08-16 14:56 UTC, cmick-aws requested changes
Finished review.
@ttymt Please Check comments and fix as needed.

2023-08-16 18:52 UTC, ttymt commented on content/intermediate/templates/conditions/index.ja.md
> +条件付きでリソースを作成するには、オプションの[条件](https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/conditions-section-structure.html)セクションをテンプレートに追加します。条件と関連する基準を決めたら、[Resources](https://docs.aws.amazo
Done

2023-08-16 18:53 UTC, ttymt commented on content/intermediate/templates/conditions/index.ja.md
> +まず、テンプレートを再利用可能にすることに集中しましょう。テンプレートに、ライフサイクル環境の入力パラメータを含む `Parameters` セクションを追加します。`EnvType` パラメータを呼び出し、使用可能な入力値として `test `と `prod` という2つの環境名の例を記述します。使用する [Amazon Machine Image](https://docs.aws.amaz
Done

2023-08-16 18:53 UTC, ttymt commented on content/intermediate/templates/conditions/index.ja.md
> +まず、テンプレートを再利用可能にすることに集中しましょう。テンプレートに、ライフサイクル環境の入力パラメータを含む `Parameters` セクションを追加します。`EnvType` パラメータを呼び出し、使用可能な入力値として `test `と `prod` という2つの環境名の例を記述します。使用する [Amazon Machine Image](https://docs.aws.amaz
Done

2023-08-16 18:53 UTC, ttymt commented on content/intermediate/templates/conditions/index.ja.md
> +::alert[詳細については、[Query for the latest Amazon Linux AMI IDs using AWS Systems Manager Parameter Store](https://aws.amazon.com/jp/blogs/compute/query-for-the-latest-amazon-linux-ami-ids-using-aws-syste
Done

2023-08-16 18:53 UTC, ttymt commented on content/intermediate/templates/conditions/index.ja.md
> +次に、[テンプレート](https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/template-anatomy.html)の `Conditions` セクションの条件の例である `isProduction` について説明します。この条件では、 `EnvType` パラメータ値が `prod` に等しいかどうかを
Done

2023-08-16 18:54 UTC, ttymt commented on content/intermediate/templates/conditions/index.ja.md
>  既存のファイルコンテンツに次のコンテンツを追加します。
Done

2023-08-16 18:54 UTC, ttymt commented on content/intermediate/templates/conditions/index.ja.md
> +次に、[テンプレート](https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/template-anatomy.html)の `Conditions` セクションの条件の例である `isProduction` について説明します。この条件では、 `EnvType` パラメータ値が `prod` に等しいかどうかを
Done

2023-08-16 18:54 UTC, ttymt commented on content/intermediate/templates/conditions/index.ja.md
> +次に、`IsProduction` 条件に基づいて条件付きでプロビジョニングするリソースに条件を関連付けます。次の例では、`Volume` リソースと `MountPoint` リソースを `IsProduction` に関連付けます。`Volume` および `MountPoint` リソースが作成されるのは、`IsProduction` 条件が満たされた場合、つまり、`EnvType` パラ
Done

2023-08-16 18:55 UTC, ttymt commented on content/intermediate/templates/conditions/index.ja.md
> +スタックを作成する時に、`test` を `envType` の値として渡すと、CloudFormation によって EC2 インスタンスリソースのみがプロビジョニングされることがわかります。更新したテンプレートを保存します。次に、AWS CloudFormation [コンソール](https://console.aws.amazon.com/cloudformation) に移動し、スタッ
Done

2023-08-16 18:55 UTC, ttymt commented on content/intermediate/templates/conditions/index.ja.md
> +* `EnvType` パラメータの値として `test` を選択します。**次へ** をクリックします。
Done

2023-08-16 18:56 UTC, ttymt commented on content/intermediate/templates/conditions/index.ja.md
> +次に、`IsProduction` 条件により、条件付きでプロパティ値を指定します。この例では、`Fn::if` [条件関数](https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-conditions.html#intrinsic-function-re
Done

2023-08-16 18:56 UTC, ttymt commented on content/intermediate/templates/conditions/index.ja.md
>  Outputs:
Done

2023-08-16 18:56 UTC, ttymt commented on content/intermediate/templates/conditions/index.ja.md
> +* [スタック出力](https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/outputs-section-structure.html#outputs-section-structure-examples)のドキュメントを参照し、テンプレートで `VolumeID` 出力を定義してください。
Done

2023-08-16 18:56 UTC, ttymt commented on content/intermediate/templates/conditions/index.ja.md
>  ![ondition-prod-update](/static/intermediate/templates/conditions/condition-prod-update.ja.png)
Done

2023-08-16 18:56 UTC, ttymt commented on content/intermediate/templates/conditions/index.ja.md
> +**タスク:** `condition-resource.yaml` テンプレートに [Outputs](https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/outputs-section-structure.html) セクションを記述してください。出力の論理IDとして `VolumeId` を指定し、`Re
Done

2023-08-16 18:56 UTC, ttymt commented on content/intermediate/templates/conditions/index.ja.md
>  スタックの`出力`セクションに移動し、`VolumeID` の出力が存在することを確認します。
Done

2023-08-16 18:56 UTC, ttymt commented on content/intermediate/index.ja.md
> +**中級編ワークショップ**の各セクションでは、あなたが書いたルールに従い、JSON や YAML 形式の Policy as Code 検証を行う [AWS CloudFormation Guard](https://github.com/aws-cloudformation/cloudformation-guard) 等のトピックについて学びます。
Done

2023-08-16 18:57 UTC, ttymt commented on content/intermediate/templates/resource-dependencies/index.ja.md
> +[AWS CloudFormation](https://aws.amazon.com/jp/cloudformation/) を使用して、テンプレートに記述したリソースをプログラム的にプロビジョニングする際、あるリソースが 1 つ以上のリソースに依存する場合があります。例えば、[Amazon Elastic Compute Cloud](https://aws.amazon.com/ec2/)
Done

2023-08-16 18:57 UTC, ttymt commented on content/intermediate/templates/resource-dependencies/index.ja.md
> +このラボでは、`DependsOn` [属性](https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/aws-attribute-dependson.html)を使用して、リソースの作成順序を明示的に定義する方法を学びます。また、`Ref` と`Fn::GetAtt` [組み込み関数](https://docs.
Done

2023-08-16 18:57 UTC, ttymt commented on content/intermediate/templates/resource-dependencies/index.ja.md
> +* `Ref` と`Fn::GetAtt` [組み込み関数](https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference.html)を使用して、リソース間の依存関係を作成
Done

2023-08-16 18:57 UTC, ttymt commented on content/intermediate/templates/resource-dependencies/index.ja.md
> +* `dependsOn` [リソース属性](https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/aws-attribute-dependson.html)の使い方を理解して、リソースの作成順序を明示的に定義
Done

2023-08-16 18:57 UTC, ttymt commented on content/intermediate/templates/resource-dependencies/index.ja.md
> +次に、新しいスタックのスタックイベントを確認しましょう。テンプレートで説明されている Amazon SNS トピックに `DependsOn` 属性を追加し、その属性の値として Amazon S3 バケットの論理 ID を指定しました。その結果、CloudFormation は、最初に `S3Bucket` リソースを作成し、次に `SNSTopic` リソースを作成しました。スタックを削除する
Done

2023-08-16 18:57 UTC, ttymt commented on content/intermediate/templates/layered-stacks/index.ja.md
> +**階層化されたスタック**では、複数のスタックで繰り返し使用できるリソースを作成できます。全てのスタックには、**エクスポート**名が必要です。この機能を利用することで、役割と責任を分けることができます。例えば、ネットワークチームは、承認された VPC デザインをテンプレートとして作成して提供できます。その後、必要に応じて、VPCスタックのエクスポートを参照するだけです。同様に、セキュリティチ
Done

2023-08-16 18:58 UTC, ttymt commented on content/intermediate/templates/resource-dependencies/index.ja.md
> +テンプレートに貼り付けたテンプレートスニペットには、Amazon SNS [Topic](https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/aws-resource-sns-topic.html)、Amazon SNS [Topic Subscription](https://docs.aws.amazon.
Done

2023-08-16 18:58 UTC, ttymt commented on content/intermediate/templates/architecting-templates/index.ja.md
> +Cloud9 の `security-groups.template` ファイルを開きます。このサンプルテンプレートでは、2 つのセキュリティグループについて説明しています。1 つは作成するロードバランサー用、もう 1 つはサンプル Web アプリケーションを実行する EC2 インスタンス用です。どちらのセキュリティグループも、前に見たのと同じ方法で VPC ID を消費することに注意してくださ
Done

2023-08-16 18:58 UTC, ttymt commented on content/intermediate/templates/policy-as-code-with-guard/index.ja.md
> +[Amazon S3 バケット](https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket.html) の下に[プロパティ](https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/aw
Done

2023-08-16 18:58 UTC, ttymt commented on content/intermediate/templates/policy-as-code-with-guard/index.ja.md
>  Properties:
Done

2023-08-16 18:58 UTC, ttymt commented on content/intermediate/templates/architecting-templates/index.ja.md
> +Cloud9 の `security-groups.template` ファイルを開きます。このサンプルテンプレートでは、2 つのセキュリティグループについて説明しています。1 つは作成するロードバランサー用、もう 1 つはサンプル Web アプリケーションを実行する EC2 インスタンス用です。どちらのセキュリティグループも、前に見たのと同じ方法で VPC ID を消費することに注意してくださ
Done

2023-08-16 18:58 UTC, ttymt commented on content/intermediate/templates/resource-dependencies/index.ja.md
> +* Topic リソースの論理 ID である `SNSTopic` は、`SNSTopicSubscription` リソースの `TopicArn` プロパティの `Ref` で参照されます。`TopicArn` プロパティには、サブスクライブする Topic の [Amazon Resource Name](https://docs.aws.amazon.com/ja_jp/general/
Done

2023-08-16 18:59 UTC, ttymt commented on content/intermediate/templates/resource-dependencies/index.ja.md
>  * `Security Group` リソースが `CREATE_COMPLETE` ステータスになると、`SecurityGroupIngress` の作成が開始されます。同様に、`SNSTopicSubscription` リソースの作成が開始されます。
Done

2023-08-16 18:59 UTC, ttymt commented on content/intermediate/templates/resource-dependencies/index.ja.md
> +* `SNSTopic` と `SecurityGroup` リソースの間には依存関係がないことにご注意ください。つまり、CloudFormation は両方のリソースの作成を並行して開始します。
Done

2023-08-16 18:59 UTC, ttymt commented on content/intermediate/templates/resource-dependencies/index.ja.md
> +5. **パラメータ**セクションで、Amazon SNS トピックサブスクリプションの E メールアドレスを入力します。準備ができたら、**次へ**をクリックします。
Done

2023-08-16 18:59 UTC, ttymt commented on content/intermediate/templates/resource-dependencies/index.ja.md
> +* Amazon EC2 インスタンスの `SecurityGroups` [プロパティ](https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-security-group.html#aws-properties-ec2-security-group-properties)
Done

2023-08-16 18:59 UTC, ttymt commented on content/intermediate/templates/dynamic-references/index.ja.md
> +このモジュールでは、CloudFormation テンプレートの[動的な参照](https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/dynamic-references.html)を使用して、[AWS Systems Manager](https://docs.aws.amazon.com/ja_jp/syst
Done

2023-08-16 18:59 UTC, ttymt commented on content/intermediate/templates/dynamic-references/index.ja.md
> +また、AWS CloudFormation テンプレート内の機密情報を参照する必要がある場合もあります。[AWS Secrets Manager](https://docs.aws.amazon.com/ja_jp/secretsmanager/latest/userguide/intro.html) を使用すると、データベースやその他のサービスの認証情報をプログラムで安全に暗号化、保存、取得で
Done

2023-08-16 19:00 UTC, ttymt commented on content/intermediate/templates/dynamic-references/index.ja.md
> +3. 次に示す手順に従って、テンプレートに記述した EC2 インスタンスのパラメータへの動的参照を作成します。
Dpme

2023-08-16 19:00 UTC, ttymt commented on content/intermediate/templates/nested-stacks/index.ja.md
>  #### 1. ネストされたスタックリソース
Done

2023-08-16 19:01 UTC, ttymt commented on content/intermediate/templates/nested-stacks/index.ja.md
>  ##### 4. VPC ネストされたスタックをデプロイ
Done

2023-08-16 19:01 UTC, ttymt commented on content/intermediate/templates/nested-stacks/index.ja.md
>  ##### 4. IAM ネストされたスタックをデプロイ
Done

2023-08-16 19:01 UTC, ttymt commented on content/intermediate/templates/package-and-deploy/index.ja.md
>  [ネストされたスタックラボ](/intermediate/templates/nested-stacks) で学んだように、 メインの CloudFormation テンプレートをデプロイする前に、これらのファイルが S3 で利用可能になっている必要があります。
Done

2023-08-16 19:01 UTC, ttymt commented on content/intermediate/templates/package-and-deploy/index.ja.md
> +一番最初に、Cloudformation テンプレートをデプロイするAWSリージョンを蹴ってします。Lambda がパッケージ化されたアーティファクトにアクセスできるようにするには、S3 バケットが Lambda と同じリージョンにある必要があります。
Done

2023-08-16 19:02 UTC, ttymt commented on content/intermediate/templates/package-and-deploy/index.ja.md
>  ディレクトリに [pip](https://pypi.org/project/pip/) が付いているので、関数コードと一緒にパッケージ化できます。
Done

2023-08-16 19:02 UTC, ttymt commented on content/intermediate/templates/architecting-templates/index.ja.md
> +次に、Cloud9 環境を作成します。これを 2 つの目的で使用します。1 つは、このラボ用のインフラストラクチャのデプロイを継続すること、もう 1 つは VPC の範囲内で DNS 設定を検証することです。Cloud9 環境をデプロイする前に、環境そのものを記述するテンプレートでどのようにエクスポートを実行するかを見てみましょう。お好みのテキストエディタで `cloud9.template`
Done

2023-08-16 19:02 UTC, ttymt commented on content/intermediate/templates/architecting-templates/index.ja.md
>  スタックの作成が開始されます。最後に、スタックのステータスが `CREATE_COMPLETE` になります。スタックの作成が進むにつれて、ワークステーションの任意のテキストエディタで `base-network.template` ファイルを開きます。次の点に注意してください。
Done

2023-08-16 19:02 UTC, ttymt commented on content/intermediate/templates/package-and-deploy/index.ja.md
>  `—parameter-overrides` オプションを設定してテンプレート内のパラメータを指定することもできます。
Done

2023-08-16 19:02 UTC, ttymt commented on content/intermediate/templates/package-and-deploy/index.ja.md
> +これは `'key=value'` のペアを含む文字列でも、[提供された json ファイル](https://docs.aws.amazon.com/ja_jp/cli/latest/userguide/cli-usage-parameters.html#cli-usage-parameters-json) 経由の文字列でもかまいません。
Done

2023-08-16 19:03 UTC, ttymt commented on content/intermediate/templates/package-and-deploy/index.ja.md
>  ##### Capabilities
Done

2023-08-16 19:03 UTC, ttymt commented on content/intermediate/templates/package-and-deploy/index.ja.md
> +そのためには、前の例で示したように、`—capabilities` フラグを使います。capabilities については、
Done

2023-08-16 19:03 UTC, ttymt commented on content/intermediate/templates/package-and-deploy/index.ja.md
>  [`aws cloudformation deploy` ドキュメント](https://docs.aws.amazon.com/cli/latest/reference/cloudformation/deploy/index.html)をご参照ください。
Done

2023-08-16 19:03 UTC, ttymt commented on content/intermediate/templates/package-and-deploy/index.ja.md
>  #### Lambda のテスト
Done

2023-08-16 19:03 UTC, ttymt commented on content/intermediate/templates/architecting-templates/index.ja.md
Done

2023-08-22 09:07 UTC, cmick-aws commented on content/intermediate/templates/conditions/index.ja.md
> +::alert[詳細については、[Query for the latest Amazon Linux AMI IDs using AWS Systems Manager Parameter Store](https://aws.amazon.com/jp/blogs/compute/query-for-the-latest-amazon-linux-ami-ids-using-aws-syste
URLが違います。

2023-08-22 09:29 UTC, cmick-aws commented on content/intermediate/templates/package-and-deploy/index.ja.md
> +一番最初に、Cloudformation テンプレートをデプロイするAWSリージョンを蹴ってします。Lambda がパッケージ化されたアーティファクトにアクセスできるようにするには、S3 バケットが Lambda と同じリージョンにある必要があります。
ごめんなさい、追加で「CloudFormation」のFの修正をお願いします。

2023-08-22 09:33 UTC, cmick-aws commented on content/intermediate/templates/package-and-deploy/index.ja.md
>  `—parameter-overrides` オプションを設定してテンプレート内のパラメータを指定することもできます。
「--」の文字が違うようです。

2023-08-22 09:33 UTC, cmick-aws commented on content/intermediate/templates/package-and-deploy/index.ja.md
> +そのためには、前の例で示したように、`—capabilities` フラグを使います。capabilities については、
「--」の文字が違うようです。

2023-08-22 09:35 UTC, cmick-aws commented on content/intermediate/templates/package-and-deploy/index.ja.md
>  ##### Capabilities
Nice！

2023-08-22 09:39 UTC, cmick-aws commented on content/intermediate/templates/architecting-templates/index.ja.md
>  スタックの作成が開始されます。最後に、スタックのステータスが `CREATE_COMPLETE` になります。スタックの作成が進むにつれて、ワークステーションの任意のテキストエディタで `base-network.template` ファイルを開きます。次の点に注意してください。
変更なしを了解しました。

2023-08-22 09:46 UTC, cmick-aws commented on content/intermediate/templates/conditions/index.ja.md
> +::alert[詳細については、[Query for the latest Amazon Linux AMI IDs using AWS Systems Manager Parameter Store](https://aws.amazon.com/jp/blogs/compute/query-for-the-latest-amazon-linux-ami-ids-using-aws-syste
Fixed

2023-08-22 09:47 UTC, cmick-aws commented on content/intermediate/templates/package-and-deploy/index.ja.md
> +一番最初に、Cloudformation テンプレートをデプロイするAWSリージョンを蹴ってします。Lambda がパッケージ化されたアーティファクトにアクセスできるようにするには、S3 バケットが Lambda と同じリージョンにある必要があります。
Fixed

2023-08-22 09:48 UTC, cmick-aws commented on content/intermediate/templates/package-and-deploy/index.ja.md
>  `—parameter-overrides` オプションを設定してテンプレート内のパラメータを指定することもできます。
Fixed

2023-08-22 09:48 UTC, cmick-aws commented on content/intermediate/templates/package-and-deploy/index.ja.md
> +そのためには、前の例で示したように、`—capabilities` フラグを使います。capabilities については、
Fixed

2023-08-22 09:52 UTC, cmick-aws approved these changes

2023-08-22 09:56 UTC, cmick-aws commented
As the ja-05-intermediate got the `main` branch changes by error, it must not merged to `main.ja` branch. We will not merge this pull request, just finish the review to the intermediate/templates section.

2023-08-22 09:56 UTC, closed without merging