Add lab duration
aws-samples/cfn101-workshop pull request #185
Opened 2022-11-18 14:40 UTC by rezabekf

*Issue #, if available:*
N/A

*Description of changes:*
This PR adds lab duration.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-11-21 19:23 UTC, mrinaudo-aws requested changes
Thank you, @rezabekf !  Please find/action on the one suggestion, otherwise lgtm!

2022-11-21 19:23 UTC, mrinaudo-aws commented on content/basics/templates/template-and-stack/index.md
> +13. On the **Review <stack_name>** page, scroll down to the bottom and click on **Submit**.
```suggestion
13. On the **Review <stack_name>** page, scroll down to the bottom and choose **Submit**.
```

2022-11-25 12:23 UTC, ConnorKirk submitted a review, later dismissed

2022-11-25 13:13 UTC, ConnorKirk approved these changes

2022-11-25 13:21 UTC, merged