Add C9 to template and stack lab
aws-samples/cfn101-workshop pull request #197
Opened 2023-04-13 08:48 UTC by rezabekf

## What does this PR do and why?

This PR adds C9 instructions to template and stack.

## Issue #, if available
N/A
## PR acceptance checklist

This checklist encourages us to confirm any changes have been analyzed to reduce risks in quality, performance, reliability, security, and maintainability.

- [ ] Added/Updated documentation if applicable.
- [x] Pre-commit checks passed.
- [x] Lint and Nag checks passed.
- [ ] If releasing a new version, have you bumped the version `make version part=<major|minor|patch>`?

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-04-24 00:48 UTC, cjhar commented
Updated, ready for review

2023-04-27 10:51 UTC, cjhar commented on content/basics/templates/template-and-stack/index.md
> +	1. In the Cloud9 terminal navigate to `code/workspace`:
Should we emphasise the Cloud9 terminal?
```suggestion
	1. In the **Cloud9 terminal** navigate to `code/workspace`:
```

2023-04-27 10:51 UTC, cjhar commented on content/basics/templates/template-and-stack/index.md
> +    1. Open the **[AWS CloudFormation](https://console.aws.amazon.com/cloudformation)** console in a new tab and check if the stack status is `CREATE_COMPLETE`.
Consistency
```suggestion
    1. Open the **[AWS CloudFormation](https://console.aws.amazon.com/cloudformation)** console in a new tab and check if the stack status is **CREATE_COMPLETE**.
```

2023-04-27 10:51 UTC, cjhar commented on content/basics/templates/template-and-stack/index.md
>  1. Go to the AWS console to update your CloudFormation Stack:
```suggestion
1. It’s now time to update your stack! Follow steps below:
```

2023-04-27 10:51 UTC, cjhar commented on content/basics/templates/template-and-stack/index.md
> +	1. In the Cloud9 terminal navigate to `code/workspace`:
```suggestion
	1. In the **Cloud9 terminal** navigate to `code/workspace`:
```

2023-04-27 10:51 UTC, cjhar commented on content/basics/templates/template-and-stack/index.md
> +    1. Open the **[AWS CloudFormation](https://console.aws.amazon.com/cloudformation)** console in a new tab and check if the stack status is `CREATE_COMPLETE`.
```suggestion
    1. Open the **[AWS CloudFormation](https://console.aws.amazon.com/cloudformation)** console in a new tab and check if the stack status is **UPDATE_COMPLETE**.
```

2023-04-27 10:51 UTC, cjhar commented on content/basics/templates/template-and-stack/index.md
>     1. Log in to the **[AWS CloudFormation Console](https://console.aws.amazon.com/cloudformation)** in a new browser tab.
```suggestion
   1. Log in to the **[AWS CloudFormation](https://console.aws.amazon.com/cloudformation)** console in a new browser tab.
```

2023-04-27 13:04 UTC, mrinaudo-aws requested changes
@rezabekf thank you!  I added suggestions - please have a look when possible!

2023-04-27 13:04 UTC, mrinaudo-aws commented on content/basics/templates/template-and-stack/index.md
> +   1. You can click the **refresh** button a few times until you see in the status **CREATE_COMPLETE**.
```suggestion
   1. Use the **refresh** button to update the page as needed, until you see the stack to be in the **CREATE_COMPLETE** status.
```

2023-04-27 13:04 UTC, mrinaudo-aws commented on content/basics/templates/template-and-stack/index.md
>  In this exercise, enable versioning on the S3 bucket. Enabled versioning will prevent objects from being deleted or
```suggestion
In this exercise, you'll enable versioning on the S3 bucket to prevent objects from being deleted or
```

2023-04-27 13:04 UTC, mrinaudo-aws commented on content/basics/templates/template-and-stack/index.md
> +    1. Run `awscli` command to create the stack. The required parameters `--stack-name` and `--template-body` has been pre-filled for you.
```suggestion
    1. Use the AWS CLI to create the stack. The required parameters `--stack-name` and `--template-body` have been pre-filled for you.
```

2023-04-27 14:21 UTC, mrinaudo-aws requested changes
@rezabekf thanks!  I added other suggestions.  In my file view, I do not seem to be able to add suggestions for other parts of the file, even if I expand the view; in addition to the suggestion that I made, can you please address this as well:

- in the Overview: "containing only Resources object": change to "containing only the `Resources` section"
- in the cleanup section: change "click" occurrences to "choose", and replace "You can click the refresh button a few times until you see in the status" using the same sentence of line `66` but with the delete status instead.

Thank you!

2023-04-27 14:21 UTC, mrinaudo-aws commented on content/basics/templates/template-and-stack/index.md
> +    1. If the `create-stack` command was successful CloudFormation will return `StackId`.
```suggestion
    1. If the `create-stack` command was successfully sent, CloudFormation will return `StackId`.
```

2023-04-27 18:48 UTC, mrinaudo-aws approved these changes
Adding 2 minor suggestions to address - otherwise LGTM.  Thank you!

2023-04-27 18:48 UTC, mrinaudo-aws commented on content/basics/templates/template-and-stack/index.md
> +This lab will start with the most basic template containing only `Resources` section, which contains a single resource declaration of the S3 bucket.
```suggestion
This lab will start with the most basic template containing only the `Resources` section, which contains a single resource declaration of the S3 bucket.
```

2023-04-27 18:48 UTC, mrinaudo-aws commented on content/basics/templates/template-and-stack/index.md
> +1. Wait for the stack to reach **DELETE_COMPLETE** status. You need to periodically select **Refresh** to see the latest stack status.
```suggestion
1. Wait for the stack to reach the **DELETE_COMPLETE** status. You need to periodically select **Refresh** to see the latest stack status.
```

2023-04-28 10:48 UTC, svozza commented on content/basics/templates/template-and-stack/index.md
> +   1. Use the **refresh** button to update the page as needed, until you see the stack to be in the **CREATE_COMPLETE** status.
```suggestion
   1. Use the **refresh** button to update the page as needed, until you see the stack has the **CREATE_COMPLETE** status.
```

2023-04-28 10:48 UTC, svozza commented on content/basics/templates/template-and-stack/index.md
> +   1. On the **Review <stack_name>** page, scroll down to the bottom and choose **Submit**.
```suggestion
   1. On the **Review <stack_name>** page, scroll to the bottom and choose **Submit**.
```

2023-04-28 10:55 UTC, sprkem approved these changes

2023-04-28 10:59 UTC, merged