intrinsic functions updated for cloud9
aws-samples/cfn101-workshop pull request #200
Opened 2023-04-14 06:57 UTC by snjkumar23

## What does this PR do and why?

Updated intrinsic function for cloud9 changes

## Issue #, if available

## PR acceptance checklist

This checklist encourages us to confirm any changes have been analyzed to reduce risks in quality, performance, reliability, security, and maintainability.

- [ ] Added/Updated documentation if applicable.
- [ Y] Pre-commit checks passed.
- [ Y] Lint and Nag checks passed.
- [ ] If releasing a new version, have you bumped the version `make version part=<major|minor|patch>`?

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-04-28 12:36 UTC, rezabekf requested changes
Left few comments

2023-04-28 12:36 UTC, rezabekf commented on content/basics/templates/intrinsic-functions/index.md
> +aws cloudformation update-stack --stack-name cfn-workshop-s3 --template-body file://intrinsic-functions.yaml --parameters '[{"ParameterKey":"AmiID","ParameterValue":"ami-id"}]'
```suggestion
aws cloudformation update-stack --stack-name cfn-workshop-ec2 --template-body file://intrinsic-functions.yaml --parameters '[{"ParameterKey":"AmiID","ParameterValue":"MyAmiId"}]'
```

2023-04-28 12:36 UTC, rezabekf commented on content/basics/templates/intrinsic-functions/index.md
> +1. Use the AWS CLI to update the stack. The required parameter `--template-body` have been pre-filled for you. Use `AmiId` which you have hardcoded in `resources.yaml` file earlier.
```suggestion
1. Use the AWS CLI to update the stack. The required parameter `--template-body` have been pre-filled for you. Replace the `ParameterValue` **MyAmiId** with  the value you have hardcoded in `resources.yaml` file earlier.
```

2023-04-28 12:36 UTC, rezabekf commented on content/basics/templates/intrinsic-functions/index.md
Please add C9 instructions to the challenge part, line 155-156

2023-04-28 14:37 UTC, snjkumar23 commented on content/basics/templates/intrinsic-functions/index.md
done

2023-04-28 14:38 UTC, snjkumar23 commented on content/basics/templates/intrinsic-functions/index.md
> +1. Use the AWS CLI to update the stack. The required parameter `--template-body` have been pre-filled for you. Use `AmiId` which you have hardcoded in `resources.yaml` file earlier.
done

2023-04-28 14:38 UTC, snjkumar23 commented on content/basics/templates/intrinsic-functions/index.md
> +aws cloudformation update-stack --stack-name cfn-workshop-s3 --template-body file://intrinsic-functions.yaml --parameters '[{"ParameterKey":"AmiID","ParameterValue":"ami-id"}]'
done

2023-05-05 08:37 UTC, rezabekf commented on content/basics/templates/intrinsic-functions/index.md
> +"StackId": "arn:aws:cloudformation:us-east-1:123456789012:stack/cfn-workshop-s3/739fafa0-e4d7-11ed-a000-12d9009553ff"
```suggestion
"StackId": "arn:aws:cloudformation:us-east-1:123456789012:stack/cfn-workshop-ec2/739fafa0-e4d7-11ed-a000-12d9009553ff"
```

2023-05-05 08:49 UTC, rezabekf approved these changes
LGMT

2023-05-05 08:49 UTC, merged