outputs changes for cloud9 integration
aws-samples/cfn101-workshop pull request #203
Opened 2023-04-14 16:15 UTC by snjkumar23

## What does this PR do and why?

Changes in outputs section for cloud9 integration

## Issue #, if available

## PR acceptance checklist

This checklist encourages us to confirm any changes have been analyzed to reduce risks in quality, performance, reliability, security, and maintainability.

- [ ] Added/Updated documentation if applicable.
- [ Y] Pre-commit checks passed.
- [ Y] Lint and Nag checks passed.
- [ ] If releasing a new version, have you bumped the version `make version part=<major|minor|patch>`?

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-04-28 13:00 UTC, rezabekf requested changes
See the inline feedback

2023-05-09 14:34 UTC, rezabekf requested changes
Please see the comment inline. The lab should be independent from resources lab. We have previously wrongly assumed, that resources lab is completed.

2023-05-09 14:34 UTC, rezabekf commented on content/basics/templates/outputs/index.md
> +1. Update the stack with new template.
```suggestion
1. Create the stack with a new template.
```

2023-05-09 14:34 UTC, rezabekf commented on content/basics/templates/outputs/index.md
> +"StackId": "arn:aws:cloudformation:us-east-1:123456789012:stack/cfn-workshop-resources/739fafa0-e4d7-11ed-a000-12d9009553ff"
Please fix to cfn-create.

Please fix the naming to `cfn-workshop-<lab-name>`

2023-05-09 14:34 UTC, rezabekf commented on content/basics/templates/outputs/index.md
> +1. You can click the **refresh** button a few times until you see in the status **UPDATE_COMPLETE**.
Could you please update this section to create new stack. This was previously wrongly assuming to update stack where we want to create new one.

2023-05-09 14:34 UTC, rezabekf commented on content/basics/templates/outputs/index.md
> +  "StackId": "arn:aws:cloudformation:us-east-1:123456789012:stack/cfn-workshop-resources/739fafa0-e4d7-11ed-a000-12d9009553ff"
please fix stack name `cfn-workshop-<lab-name>`

2023-05-09 14:34 UTC, rezabekf commented on content/basics/templates/outputs/index.md
> +1. Click on the stack name, for example **cfn-workshop-resources**.
please fix stack name `cfn-workshop-<lab-name>`

2023-05-09 16:16 UTC, snjkumar23 commented on content/basics/templates/outputs/index.md
> +1. View the output value on the [AWS CloudFormation console](https://console.aws.amazon.com/cloudformation), in the _Outputs_ tab.
incorporated

2023-05-09 16:36 UTC, rezabekf commented on content/basics/templates/outputs/index.md
> +1. You can click the **refresh** button a few times until you see in the status **UPDATE_COMPLETE**.
I will do this.

2023-05-11 09:34 UTC, sdangol commented on content/basics/templates/outputs/index.md
> +:::code{language=shell showLineNumbers=false showCopyAction=false}
```suggestion
:::code{language=shell showLineNumbers=false showCopyAction=true}
```

2023-05-11 09:35 UTC, sdangol commented on content/basics/templates/outputs/index.md
> +  :::code{language=shell showLineNumbers=false showCopyAction=false}
```suggestion
  :::code{language=shell showLineNumbers=false showCopyAction=true}
```

2023-05-11 13:04 UTC, rezabekf requested changes
Small changes required.

2023-05-11 13:04 UTC, rezabekf commented on content/basics/templates/outputs/index.md
> +1. In **Template source**, choose **Upload a template file**.
```suggestion
1. In **Specify template**, choose **Upload a template file**.
```

2023-05-11 13:04 UTC, rezabekf commented on content/basics/templates/outputs/index.md
> +1. In **Template source**, choose **Upload a template file**.
```suggestion
1. In **Specify template**, choose **Upload a template file**.
```

2023-05-11 13:04 UTC, rezabekf commented on content/basics/templates/outputs/index.md
> +1. In **Template source**, choose **Upload a template file**.
```suggestion
1. In **Specify template**, choose **Upload a template file**.
```

2023-05-11 13:04 UTC, rezabekf commented on content/basics/templates/outputs/index.md
> +1. On the **Review <stack_name>** page, scroll down to the bottom and click on **Update stack**.
```suggestion
1. On the **Review <stack_name>** page, scroll down to the bottom and click on **Submit**.
```

2023-05-11 13:55 UTC, rezabekf requested changes
Please resolve all the changes requested. There is quite a few required to do second review.

2023-05-11 14:49 UTC, snjkumar23 commented
> Please resolve all the changes requested. There is quite a few required to do second review.

I resolved all changes already as per your review comments, are'nt they visible in latest commit

2023-05-12 08:26 UTC, rezabekf commented
Sorry @snjkumar23 , GitHub was down yesterday and was behaving weirdly, so I couldn't see the request has been implemented...looking now...

2023-05-12 08:31 UTC, rezabekf approved these changes
LGMT

2023-05-12 08:32 UTC, merged