multi region  changes for cloud9 integration
aws-samples/cfn101-workshop pull request #205
Opened 2023-04-14 17:20 UTC by snjkumar23

## What does this PR do and why?

Changes for Multi region for cloud9 integration

## Issue #, if available

## PR acceptance checklist

This checklist encourages us to confirm any changes have been analyzed to reduce risks in quality, performance, reliability, security, and maintainability.

- [ ] Added/Updated documentation if applicable.
- [ Y] Pre-commit checks passed.
- [ Y] Lint and Nag checks passed.
- [ ] If releasing a new version, have you bumped the version `make version part=<major|minor|patch>`?

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-05-09 15:03 UTC, sdangol requested changes
Added comments

2023-05-09 16:28 UTC, snjkumar23 commented
incorporated review comments

2023-05-11 09:47 UTC, sdangol commented on content/basics/operations/multi-region-latest-ami/index.md
Indentation issues in line 29 to 34 https://github.com/aws-samples/cfn101-workshop/pull/205/files#diff-04d62957d44df521b5009af7b61d0bc2d0ac49bca3a68fe7f758bed0be6d5e15R29-R34

2023-05-11 09:56 UTC, sdangol commented on content/basics/operations/multi-region-latest-ami/index.md
> +1. Choose **Create stack** from the top-right side of the page.
```suggestion
1. Choose **Create stack (With new resources (Standard)** from the top-right side of the page.
```

2023-05-11 10:00 UTC, sdangol commented on content/basics/operations/multi-region-latest-ami/index.md
>  1. For **EnvironmentType** select the different environment than is listed. For example if you have **Dev** selected, choose **Test** and click **Next**.
```suggestion
1. For **EnvironmentType** select the environment from drop down list, for example **Test** and click **Next**..
```

2023-05-11 10:02 UTC, sdangol commented on content/basics/operations/multi-region-latest-ami/index.md
>  ::expand[![update-2](/static/basics/operations/multi-region-latest-ami/update-2.gif)]{header="How do I update a Stack?"}
This gif shows how to update a stack, which is not the case as in the instruction. Maybe this could be removed.

2023-05-11 10:03 UTC, sdangol commented on content/basics/operations/multi-region-latest-ami/index.md
Please add the cleanup instructions as well

2023-05-15 10:52 UTC, sdangol commented on content/basics/operations/multi-region-latest-ami/index.md
> +   Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'
```suggestion
AmiID:
  Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
  Description: The ID of the AMI.
  Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'
```

2023-05-15 14:17 UTC, snjkumar23 commented
> Few more changes

done

2023-05-17 08:45 UTC, sdangol approved these changes
LGTM

2023-05-17 09:41 UTC, rezabekf approved these changes
LGMT

2023-05-17 09:41 UTC, merged