Added cloud9 instructions for helper-scripts lesson
aws-samples/cfn101-workshop pull request #206
Opened 2023-04-17 08:50 UTC by cjhar

## What does this PR do and why?

Added guidance to use Cloud9 dev environment for helper-scripts lesson

## Issue #, if available

## PR acceptance checklist

This checklist encourages us to confirm any changes have been analyzed to reduce risks in quality, performance, reliability, security, and maintainability.

- [ ] Added/Updated documentation if applicable.
- [X] Pre-commit checks passed.
- [X] Lint and Nag checks passed.
- [ ] If releasing a new version, have you bumped the version `make version part=<major|minor|patch>`?

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-05-01 11:37 UTC, cjhar commented
Ready for review, thanks!

2023-05-09 13:52 UTC, sdangol commented on content/basics/operations/helper-scripts/index.md
> +  aws cloudformation update-stack --stack-name cfn-workshop-ec2 \
```suggestion
  aws cloudformation update-stack --stack-name cfn-workshop-resources \
```

2023-05-09 13:52 UTC, sdangol commented on content/basics/operations/helper-scripts/index.md
> +  "StackId": "arn:aws:cloudformation:us-east-1:123456789012:stack/cfn-workshop-ec2/96d87030-e809-11ed-a82c-0eb19aaeb30f"
```suggestion
  "StackId": "arn:aws:cloudformation:us-east-1:123456789012:stack/cfn-workshop-resources/96d87030-e809-11ed-a82c-0eb19aaeb30f"
```

2023-05-09 13:56 UTC, sdangol commented on content/basics/operations/helper-scripts/index.md
>  1. Click on the stack name, for example **cfn-workshop-ec2**.
```suggestion
1. Click on the stack name, for example **cfn-workshop-resources**.
```

2023-05-09 15:05 UTC, sdangol requested changes
Please update the naming conventions and change the command to create the stack

2023-05-10 03:14 UTC, cjhar commented
Thank you for review and suggestions, all incorporated and updated sample images. Note I removed the Availability Zone ID content as we don't need to trigger an initial EC2 instance replacement when we create all new resources. Estimated timing confirmed.

**Tested end2end**

2023-05-11 10:35 UTC, sdangol commented on content/basics/operations/helper-scripts/index.md
> +5. Verify the new instance was deployed and is functional
Please put inside the tabs

2023-05-11 11:25 UTC, sdangol commented on content/basics/operations/helper-scripts/index.md
>  1. In the pop-up window click on **Delete stack**.
```suggestion
1. In the pop-up window click on **Delete**.
```

2023-05-11 11:27 UTC, sdangol requested changes
Added some more changes

2023-05-15 11:59 UTC, sdangol submitted a review, later dismissed
LGTM

2023-05-15 14:25 UTC, rezabekf approved these changes
LGMT

2023-05-15 14:25 UTC, merged