Cloud9 integration for Session_manager
aws-samples/cfn101-workshop pull request #208
Opened 2023-04-18 14:40 UTC by snjkumar23

## What does this PR do and why?

Cloud9 Changes for Session Manager section

## Issue #, if available

## PR acceptance checklist

This checklist encourages us to confirm any changes have been analyzed to reduce risks in quality, performance, reliability, security, and maintainability.

- [ ] Added/Updated documentation if applicable.
- [Y ] Pre-commit checks passed.
- [ Y] Lint and Nag checks passed.
- [ ] If releasing a new version, have you bumped the version `make version part=<major|minor|patch>`?

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-05-09 16:35 UTC, rezabekf requested changes
Updated local development.

2023-05-09 16:35 UTC, rezabekf commented on content/basics/operations/session-manager/index.md
> +2. Use the AWS CLI to update the stack. The required parameter `--template-body` have been pre-filled for you.
```suggestion
2. Use the AWS CLI to create the stack. The required parameter `--template-body` have been pre-filled for you.
```

2023-05-09 16:35 UTC, rezabekf commented on content/basics/operations/session-manager/index.md
> +  aws cloudformation update-stack --stack-name cfn-workshop-resources --template-body file://session-manager.yaml --parameters ParameterKey="EnvironmentType",ParameterValue="Dev" --capabilities CAPAB
```suggestion
  aws cloudformation create-stack --stack-name cfn-workshop-session-manager --template-body file://session-manager.yaml --parameters ParameterKey="EnvironmentType",ParameterValue="Dev" --capabilities CAPABILITY_NAMED_IAM
```

2023-05-09 16:35 UTC, rezabekf commented on content/basics/operations/session-manager/index.md
> +3. If the `update-stack` command was successfully sent, CloudFormation will return `StackId`.
```suggestion
3. If the `create-stack` command was successfully sent, CloudFormation will return `StackId`.
```

2023-05-09 16:35 UTC, rezabekf commented on content/basics/operations/session-manager/index.md
> +  "StackId": "arn:aws:cloudformation:us-east-1:123456789012:stack/cfn-workshop-resources/739fafa0-e4d7-11ed-a000-12d9009553ff"
```suggestion
  "StackId": "arn:aws:cloudformation:us-east-1:123456789012:stack/cfn-workshop-session-manager/739fafa0-e4d7-11ed-a000-12d9009553ff"
```

2023-05-09 16:35 UTC, rezabekf commented on content/basics/operations/session-manager/index.md
> +4. Open the **[AWS CloudFormation](https://console.aws.amazon.com/cloudformation)** console in a new tab and check if the stack status is **UPDATE_COMPLETE**.
```suggestion
4. Open the **[AWS CloudFormation](https://console.aws.amazon.com/cloudformation)** console in a new tab and check if the stack status is **CREATE_COMPLETE**.
```

2023-05-09 16:35 UTC, rezabekf commented on content/basics/operations/session-manager/index.md
>  1. On the **Review <stack_name>** page, scroll down to the bottom and tick **I acknowledge that AWS CloudFormation might create IAM resources** check box, then click on **Update stack**.
```suggestion
1. On the **Review <stack_name>** page, scroll down to the bottom and tick **I acknowledge that AWS CloudFormation might create IAM resources** check box, then click on **Create stack**.
```

2023-05-09 16:35 UTC, snjkumar23 commented
incorporated changes

2023-05-17 05:13 UTC, snjkumar23 commented
> Updated local development.

2023-05-17 05:13 UTC, closed without merging