Cloud9 integration for Conditions
aws-samples/cfn101-workshop pull request #210
Opened 2023-04-18 15:45 UTC by snjkumar23

## What does this PR do and why?

Cloud9 Changes for Conditions sections

## Issue #, if available

## PR acceptance checklist

This checklist encourages us to confirm any changes have been analyzed to reduce risks in quality, performance, reliability, security, and maintainability.

- [Y ] Added/Updated documentation if applicable.
- [ Y] Pre-commit checks passed.
- [ ] Lint and Nag checks passed.
- [ ] If releasing a new version, have you bumped the version `make version part=<major|minor|patch>`?

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-04-24 07:15 UTC, cjhar commented on content/intermediate/templates/conditions/index.md
> +   `aws s3 cp code/workspace/condition-resource.yaml s3://cfn-workshop-01-{accountid}`
Can we please use code blocks to make it clearer and neater?
`:::code{language=shell showLineNumbers=false showCopyAction=true}
aws s3 cp code/workspace/condition-resource.yaml s3://cfn-workshop-01-{accountid}
:::`

2023-04-24 07:16 UTC, cjhar commented on content/intermediate/templates/conditions/index.md
> +     `https://cfn-workshop-01-{accountid}.s3.amazonaws.com/condition-resource.yaml`
comment block
`:::code{language=shell showLineNumbers=false showCopyAction=true}
https://cfn-workshop-01-{accountid}.s3.amazonaws.com/{template-name}.yaml
:::`

2023-04-24 07:17 UTC, cjhar commented on content/intermediate/templates/conditions/index.md
> +        `aws s3 cp code/workspace/condition-resource.yaml s3://cfn-workshop-01-{accountid}`
comment block

2023-04-24 07:17 UTC, cjhar commented on content/intermediate/templates/conditions/index.md
> +        `https://cfn-workshop-01-{accountid}.s3.amazonaws.com/condition-resource.yaml`
comment block

2023-04-24 07:17 UTC, cjhar commented on content/intermediate/templates/conditions/index.md
> +     `https://cfn-workshop-01-{accountid}.s3.amazonaws.com/condition-resource.yaml`
comment block

2023-04-24 07:17 UTC, cjhar commented on content/intermediate/templates/conditions/index.md
> +   `aws s3 cp code/workspace/condition-resource.yaml s3://cfn-workshop-01-{accountid}`
comment block

2023-04-24 07:17 UTC, cjhar commented on content/intermediate/templates/conditions/index.md
> +   `aws s3 cp code/workspace/condition-resource.yaml s3://cfn-workshop-01-{accountid}`
comment block

2023-04-26 07:24 UTC, cjhar commented on content/intermediate/templates/conditions/index.md
> +   `aws s3 cp code/workspace/condition-resource.yaml s3://cfn-workshop-01-{accountid}`
```suggestion
:::code{language=shell showLineNumbers=false showCopyAction=true}
aws s3 cp code/workspace/condition-resource.yaml s3://cfn-workshop-01-{accountid}
:::
```

2023-04-26 07:25 UTC, cjhar commented on content/intermediate/templates/conditions/index.md
> +     `https://cfn-workshop-01-{accountid}.s3.amazonaws.com/condition-resource.yaml`
```suggestion
:::code{language=shell showLineNumbers=false showCopyAction=true}
https://cfn-workshop-01-{accountid}.s3.amazonaws.com/condition-resource.yaml
:::
```

2023-04-26 07:26 UTC, cjhar commented on content/intermediate/templates/conditions/index.md
> +     `https://cfn-workshop-01-{accountid}.s3.amazonaws.com/condition-resource.yaml`
```suggestion
:::code{language=shell showLineNumbers=false showCopyAction=true}
https://cfn-workshop-01-{accountid}.s3.amazonaws.com/condition-resource.yaml
:::
```

2023-04-26 07:26 UTC, cjhar commented on content/intermediate/templates/conditions/index.md
> +        `https://cfn-workshop-01-{accountid}.s3.amazonaws.com/condition-resource.yaml`
```suggestion
:::code{language=shell showLineNumbers=false showCopyAction=true}
https://cfn-workshop-01-{accountid}.s3.amazonaws.com/condition-resource.yaml
:::
```

2023-05-11 16:42 UTC, sdangol commented on content/intermediate/templates/conditions/index.md
> +1. Choose **Create stack**. You can view the progress of the stack being created in the CloudFormation console.
```suggestion
1. Choose **Submit**. You can view the progress of the stack being created in the CloudFormation console.
```

2023-05-11 17:08 UTC, sdangol commented on content/intermediate/templates/conditions/index.md
Indentation issue in line [286 - 289](https://github.com/aws-samples/cfn101-workshop/pull/210/files#diff-8487daf746d800371c656673b543b8d5a4fb4e18415b40284a4ca07b0b2053f3R286-R289)

2023-05-11 17:10 UTC, sdangol commented on content/intermediate/templates/conditions/index.md
> +  "StackId": "arn:aws:cloudformation:us-east-1:123456789012:stack/cfn-workshop-prod/739fafa0-e4d7-11ed-a000-12d9009553ff"
```suggestion
  "StackId": "arn:aws:cloudformation:us-east-1:123456789012:stack/cfn-workshop-condition-prod/739fafa0-e4d7-11ed-a000-12d9009553ff"
```

2023-05-11 17:10 UTC, sdangol commented on content/intermediate/templates/conditions/index.md
> +1. Choose **Update stack**. You can view the progress of the stack being created in the CloudFormation console.
```suggestion
1. Choose **Submit**. You can view the progress of the stack being created in the CloudFormation console.
```

2023-05-11 17:11 UTC, sdangol requested changes
Please have a look at the comments

2023-05-12 05:48 UTC, cjhar requested changes
Thanks, content is good just some formatting and minor corrections. End to end tested okay

2023-05-12 05:48 UTC, cjhar commented on content/intermediate/templates/conditions/index.md
> +aws cloudformation create-stack --stack-name cfn-workshop-condition-test --template-body file://condition-resource.yaml --parameters ParameterKey="EnvType",ParameterValue="test"
```suggestion
aws cloudformation create-stack --stack-name cfn-workshop-condition-test \
--template-body file://condition-resource.yaml \
--parameters ParameterKey="EnvType",ParameterValue="test"
```

2023-05-12 05:48 UTC, cjhar commented on content/intermediate/templates/conditions/index.md
> +1. Use the AWS CLI to create the stack. The required parameter `--template-body` have been pre-filled for you.
```suggestion
1. Use the AWS CLI to create the stack. The required parameters have been pre-filled for you.
```

2023-05-12 05:48 UTC, cjhar commented on content/intermediate/templates/conditions/index.md
> +1. Use the AWS CLI to create the stack. The required parameter `--template-body` have been pre-filled for you.
```suggestion
1. Use the AWS CLI to create the stack. The required parameters have been pre-filled for you.
```

2023-05-12 05:48 UTC, cjhar commented on content/intermediate/templates/conditions/index.md
> +aws cloudformation create-stack --stack-name cfn-workshop-condition-prod --template-body file://condition-resource.yaml --parameters ParameterKey="EnvType",ParameterValue="prod"
```suggestion
aws cloudformation create-stack --stack-name cfn-workshop-condition-prod \
--template-body file://condition-resource.yaml \
--parameters ParameterKey="EnvType",ParameterValue="prod"
```

2023-05-12 05:48 UTC, cjhar commented on content/intermediate/templates/conditions/index.md
> +1. Use the AWS CLI to create the stack. The required parameter `--template-body` have been pre-filled for you.
```suggestion
1. Use the AWS CLI to create the stack. The required parameters have been pre-filled for you.
```

2023-05-12 05:48 UTC, cjhar commented on content/intermediate/templates/conditions/index.md
> +aws cloudformation create-stack --stack-name cfn-workshop-condition-property-test --template-body file://condition-resource-property.yaml --parameters ParameterKey="EnvType",ParameterValue="test"
```suggestion
aws cloudformation create-stack --stack-name cfn-workshop-condition-property-test \
--template-body file://condition-resource-property.yaml \
--parameters ParameterKey="EnvType",ParameterValue="test"
```

2023-05-12 05:48 UTC, cjhar commented on content/intermediate/templates/conditions/index.md
> +1. Choose **Create stack**. You can view the progress of the stack being created in the CloudFormation console.
```suggestion
1. Choose **Submit**. You can view the progress of the stack being created in the CloudFormation console.
```

2023-05-12 05:48 UTC, cjhar commented on content/intermediate/templates/conditions/index.md
> +1. Use the AWS CLI to update the stack. The required parameter `--template-body` have been pre-filled for you.
```suggestion
1. Use the AWS CLI to update the stack. The required parameters have been pre-filled for you.
```

2023-05-12 05:48 UTC, cjhar commented on content/intermediate/templates/conditions/index.md
> +  aws cloudformation update-stack --stack-name cfn-workshop-condition-prod --template-body file://condition-resource.yaml --parameters ParameterKey="EnvType",ParameterValue="prod"
```suggestion
  aws cloudformation update-stack --stack-name cfn-workshop-condition-prod \
  --template-body file://condition-resource.yaml \
  --parameters ParameterKey="EnvType",ParameterValue="prod"
```

2023-05-15 02:11 UTC, cjhar reviewed
Thanks Sanjeev, looks good but I would break up the Challenge command on line #302
```
aws cloudformation update-stack --stack-name cfn-workshop-condition-prod \
--template-body file://condition-resource.yaml \
--parameters ParameterKey="EnvType",ParameterValue="prod"```

2023-05-15 05:51 UTC, snjkumar23 commented
> Thanks Sanjeev, looks good but I would break up the Challenge command on line #302
> 
> ```
> aws cloudformation update-stack --stack-name cfn-workshop-condition-prod \
> --template-body file://condition-resource.yaml \
> --parameters ParameterKey="EnvType",ParameterValue="prod"```
> ```

done

2023-05-15 06:16 UTC, cjhar reviewed
LGTM

2023-05-15 06:16 UTC, cjhar approved these changes

2023-05-15 12:42 UTC, merged