dynamic-references updated for Cloud9
aws-samples/cfn101-workshop pull request #211
Opened 2023-04-20 09:30 UTC by cjhar

## What does this PR do and why?

Updated instructions to use Cloud9 dev environment

## Issue #, if available

## PR acceptance checklist

This checklist encourages us to confirm any changes have been analyzed to reduce risks in quality, performance, reliability, security, and maintainability.

- [ ] Added/Updated documentation if applicable.
- [X] Pre-commit checks passed.
- [X] Lint and Nag checks passed.
- [ ] If releasing a new version, have you bumped the version `make version part=<major|minor|patch>`?

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-04-30 12:26 UTC, cjhar commented
Updated to use CLI for Cloud9

2023-05-10 07:54 UTC, cjhar commented
Timing was ~30 minutes waiting for RDS cfn creation. This lesson doesn't have an estimated timings though.

**Tested end2end**

2023-05-15 12:28 UTC, sdangol commented on content/intermediate/templates/dynamic-references/index.md
Indentation issue in line [21](https://github.com/aws-samples/cfn101-workshop/pull/211/files#diff-39846b770c89aa9aa10da824def06bde08f862a9b67bff7183e9df5a1059de44R21)

2023-05-15 12:38 UTC, sdangol commented on content/intermediate/templates/dynamic-references/index.md
>      1. change directory to `code/workspace/dynamic-references`.
```suggestion
    1. Change directory to `code/workspace/dynamic-references`.
```

2023-05-15 12:47 UTC, sdangol commented on content/intermediate/templates/dynamic-references/index.md
Capitalize the sentences in [138 and 139](https://github.com/aws-samples/cfn101-workshop/pull/211/files#diff-39846b770c89aa9aa10da824def06bde08f862a9b67bff7183e9df5a1059de44R138-R139)

2023-05-15 13:41 UTC, sdangol commented on content/intermediate/templates/dynamic-references/index.md
>     ::alert[A secret in AWS Secrets Manager has [*versions*](https://docs.aws.amazon.com/secretsmanager/latest/userguide/getting-started.html#term_version) holding copies of the encrypted secret value
```suggestion
   ::alert[A secret in AWS Secrets Manager has [*versions*](https://docs.aws.amazon.com/secretsmanager/latest/userguide/getting-started.html#term_version) holding copies of the encrypted secret value. When you change the secret value, Secrets Manager creates a new version. A secret always has a version with the staging label `AWSCURRENT`, which is the current secret value. If required, you can modify this string specifying a *version-stage* or *version-id* as such: `'{{resolve:secretsmanager:prod-DatabaseConnParams:SecretString:RDS_HOSTNAME:<version-stage>:<version-id>}}'`. When you do not specify a version, CloudFormation defaults to resolving the secret associated with the stage `AWSCURRENT`.]{type="info"}
```

2023-05-15 13:58 UTC, sdangol commented
I was getting an error `Cannot find version 8.0.26 for mysql` when trying to deploy the`cfn-workshop-dynamic-references-database` stack. Can you please check

2023-05-15 14:41 UTC, sdangol requested changes
Added some feedbacks

2023-05-16 11:31 UTC, cjhar commented on content/intermediate/templates/dynamic-references/index.md
Fixed

2023-05-16 11:33 UTC, cjhar commented on content/intermediate/templates/dynamic-references/index.md
>      1. change directory to `code/workspace/dynamic-references`.
Fixed

2023-05-16 11:33 UTC, cjhar commented on content/intermediate/templates/dynamic-references/index.md
Fixed

2023-05-16 11:36 UTC, cjhar commented on content/intermediate/templates/dynamic-references/index.md
>     In the template you just used, database connection parameters are retrieved during stack runtime using a dynamic string. You retrieved the value for a given key, such as `RDS_HOSTNAME`, with: `'{{
Fixed

2023-05-16 11:38 UTC, cjhar commented on content/intermediate/templates/dynamic-references/index.md
>     ::alert[A secret in AWS Secrets Manager has [*versions*](https://docs.aws.amazon.com/secretsmanager/latest/userguide/getting-started.html#term_version) holding copies of the encrypted secret value
Fixed

2023-05-17 08:53 UTC, sdangol approved these changes
LGTM

2023-05-17 09:47 UTC, rezabekf commented
> 

Perfect, I have added lab duration.

2023-05-17 10:37 UTC, rezabekf approved these changes
This was the big one. Thanks all for contributing! LGMT

2023-05-17 10:37 UTC, merged