packge and deploy lab support for Cloud9
aws-samples/cfn101-workshop pull request #220
Opened 2023-04-28 17:01 UTC by AvinashSeelam9

## What does this PR do and why?
This PR is to provide Cloud9 support for package and deploy lab

_Describe in detail what your merge request does and why._
This PR is to provide Cloud9 support for package and deploy lab
## Issue #, if available

## PR acceptance checklist

This checklist encourages us to confirm any changes have been analyzed to reduce risks in quality, performance, reliability, security, and maintainability.

- [x] Added/Updated documentation if applicable.
- [x] Pre-commit checks passed.
- [x] Lint and Nag checks passed.
- [ ] If releasing a new version, have you bumped the version `make version part=<major|minor|patch>`?

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-05-11 06:18 UTC, cjhar reviewed
LGTM but no **Clean Up** section leaving a cfn stack and S3 bucket

2023-05-17 06:48 UTC, cjhar requested changes
Thanks only a couple of small fixes, plus the below that I couldn't suggest here
line 74 The `aws cloudformation package` performs the following actions:
line 87 aws s3 mb s3://example-bucket-name --region us-east-1
line 155 We know that `package` will generate ZIP files, so even there is no `.zip` extension you can still `unzip` it.
line 201 :::code{language=json showLineNumbers=false showCopyAction=false}

2023-05-17 06:48 UTC, cjhar commented on content/intermediate/templates/package-and-deploy/index.md
>      --region eu-west-1 \
```suggestion
    --region us-east-1 \
```

2023-05-17 06:48 UTC, cjhar commented on content/intermediate/templates/package-and-deploy/index.md
> +      1. In the pop-up window click on Delete stack.
```suggestion
      1. In the pop-up window choose **Delete**.
```

2023-05-17 10:45 UTC, cjhar submitted a review, later dismissed
LGTM

2023-05-18 16:45 UTC, rezabekf approved these changes
LGMT

2023-05-18 16:45 UTC, merged