add cloud9 instruction in the drift-detection
aws-samples/cfn101-workshop pull request #221
Opened 2023-04-30 04:41 UTC by shubham-amaz

## What does this PR do and why?

add cloud9 instruction in the drift-detection

## Issue #, if available

## PR acceptance checklist

This checklist encourages us to confirm any changes have been analyzed to reduce risks in quality, performance, reliability, security, and maintainability.

- [ ] Added/Updated documentation if applicable.
- [y] Pre-commit checks passed.
- [y] Lint and Nag checks passed.
- [ ] If releasing a new version, have you bumped the version `make version part=<major|minor|patch>`?

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-05-11 07:53 UTC, cjhar reviewed
Thanks Shubham, I've added some suggestions for things to fix. We've also standardised the stack name and "show copy button" for stdout.
You will need to fix the stack names in the **Clean Up** section too!

2023-05-11 07:53 UTC, cjhar commented on content/intermediate/operations/drift-detection/index.md
> +    aws cloudformation create-stack --stack-name drift-detection-workshop --template-body file://drift-detection-workshop.yaml
```suggestion
    aws cloudformation create-stack --stack-name cfn-workshop-drift-detection --template-body file://drift-detection-workshop.yaml
```

2023-05-11 07:53 UTC, cjhar commented on content/intermediate/operations/drift-detection/index.md
> +    "StackId": "arn:aws:cloudformation:us-east-1:123456789012:stack/drift-detection-workshop/739fafa0-e4d7-11ed-a000-12d9009553ff"
```suggestion
    "StackId": "arn:aws:cloudformation:us-east-1:123456789012:stack/cfn-workshop-drift-detection/739fafa0-e4d7-11ed-a000-12d9009553ff"
```

2023-05-11 07:53 UTC, cjhar commented on content/intermediate/operations/drift-detection/index.md
> +   1. Choose **Create stack**.
```suggestion
   1. Choose **Submit**.
```

2023-05-11 07:53 UTC, cjhar commented on content/intermediate/operations/drift-detection/index.md
> +   1. Enter a stack name. For example, specify `drift-detection-workshop`. Choose **Next**.
```suggestion
   1. Enter a stack name. For example, specify `cfn-workshop-drift-detection`. Choose **Next**.
```

2023-05-11 07:53 UTC, cjhar commented on content/intermediate/operations/drift-detection/index.md
> +    :::code{language=shell showLineNumbers=false showCopyAction=true}
```suggestion
    :::code{language=shell showLineNumbers=false showCopyAction=false}
```

2023-05-11 07:53 UTC, cjhar commented on content/intermediate/operations/drift-detection/index.md
>  4. Navigate to the [CloudFormation Console](https://console.aws.amazon.com/cloudformation/).
```suggestion
```

2023-05-11 07:53 UTC, cjhar commented on content/intermediate/operations/drift-detection/index.md
>  5. Choose your stack as before.
```suggestion
```

2023-05-11 07:53 UTC, cjhar commented on content/intermediate/operations/drift-detection/index.md
> +    aws cloudformation update-stack --stack-name cfn-workshop-s3 --template-body file://template-and-stack.yaml
```suggestion
    aws cloudformation update-stack --stack-name cfn-workshop-drift-detection --template-body file://template-and-stack.yaml
```

2023-05-11 07:53 UTC, cjhar commented on content/intermediate/operations/drift-detection/index.md
> +    :::code{language=shell showLineNumbers=false showCopyAction=true}
```suggestion
    :::code{language=shell showLineNumbers=false showCopyAction=false}
```

2023-05-11 07:53 UTC, cjhar commented on content/intermediate/operations/drift-detection/index.md
> +    "StackId": "arn:aws:cloudformation:us-east-1:123456789012:stack/cfn-workshop-s3/739fafa0-e4d7-11ed-a000-12d9009553ff"
```suggestion
    "StackId": "arn:aws:cloudformation:us-east-1:123456789012:stack/cfn-workshop-drift-detection/739fafa0-e4d7-11ed-a000-12d9009553ff"
```

2023-05-11 07:53 UTC, cjhar commented on content/intermediate/operations/drift-detection/index.md
> +    :::code{language=shell showLineNumbers=false showCopyAction=true}
```suggestion
    :::code{language=shell showLineNumbers=false showCopyAction=false}
```

2023-05-11 07:53 UTC, cjhar commented on content/intermediate/operations/drift-detection/index.md
> +   1. Choose **Update Stack**.
```suggestion
   1. Choose **Submit**.
```

2023-05-11 07:53 UTC, cjhar commented on content/intermediate/operations/drift-detection/index.md
> +	1. In the **Cloud9 terminal** navigate to `code/workspace`:
```suggestion
	1. In the **Cloud9 terminal** ensure your working directory is `code/workspace/drift-detection`:
```

2023-05-11 07:53 UTC, cjhar commented on content/intermediate/operations/drift-detection/index.md
> +    cd cfn101-workshop/code/workspace
```suggestion
    cd cfn101-workshop/code/workspace/drift-detection
```

2023-05-11 07:53 UTC, cjhar commented on content/intermediate/operations/drift-detection/index.md
> +    ::::
Need to add in the stack drift check
```suggestion
 1. Choose the **Stack info** tab.
   1. From **Stack actions**, choose **Detect Drift**.
   1. Wait a few seconds for drift detection to complete.
   1. You should now see that the drift status is `IN_SYNC`, showing that the template and resource match.
    ::::
```

2023-05-11 07:53 UTC, cjhar commented on content/intermediate/operations/drift-detection/index.md
> +    cd cfn101-workshop/code/workspace
```suggestion
    cd cfn101-workshop/code/workspace/drift-detection
```

2023-05-11 07:53 UTC, cjhar commented on content/intermediate/operations/drift-detection/index.md
> +	1. In the **Cloud9 terminal** navigate to `code/workspace`:
```suggestion
	1. In the **Cloud9 terminal** ensure your working directory is `code/workspace/drift-detection`:
```

2023-05-11 07:53 UTC, cjhar commented on content/intermediate/operations/drift-detection/index.md
> +    aws cloudformation update-stack --stack-name cfn-workshop-s3 --template-body file://template-and-stack.yaml
```suggestion
    aws cloudformation update-stack --stack-name cfn-workshop-drift-detection-challenge --template-body file://drift-detection-challenge.yaml
```

2023-05-11 07:53 UTC, cjhar commented on content/intermediate/operations/drift-detection/index.md
> +    :::code{language=shell showLineNumbers=false showCopyAction=true}
```suggestion
    :::code{language=shell showLineNumbers=false showCopyAction=false}
```

2023-05-11 07:53 UTC, cjhar commented on content/intermediate/operations/drift-detection/index.md
> +    "StackId": "arn:aws:cloudformation:us-east-1:123456789012:stack/cfn-workshop-s3/739fafa0-e4d7-11ed-a000-12d9009553ff"
```suggestion
    "StackId": "arn:aws:cloudformation:us-east-1:123456789012:stack/cfn-workshop-drift-detection-challenge/739fafa0-e4d7-11ed-a000-12d9009553ff"
```

2023-05-11 07:53 UTC, cjhar commented on content/intermediate/operations/drift-detection/index.md
> +   1. Enter a stack name, for example `drift-detection-challenge` and choose **Next**.
```suggestion
   1. Enter a stack name, for example `cfn-workshop-drift-detection-challenge` and choose **Next**.
```

2023-05-11 07:53 UTC, cjhar commented on content/intermediate/operations/drift-detection/index.md
> +   1. In the next page, choose **Create stack**.
```suggestion
   1. In the next page, choose **Submit**.
```

2023-05-11 07:53 UTC, cjhar commented on content/intermediate/operations/drift-detection/index.md
> +   1. Once the stack is created, select the `drift-detection-challenge` stack and choose **Resources**. Take a note of the **Physical ID** for `Instance1`, for example `i-1234567890abcdef0`.
```suggestion
   1. Once the stack is created, select the `cfn-workshop-drift-detection-challenge` stack and choose **Resources**. Take a note of the **Physical ID** for `Instance1`, for example `i-1234567890abcdef0`.
```

2023-05-11 07:53 UTC, cjhar commented on content/intermediate/operations/drift-detection/index.md
> +    ::::
```suggestion
1. Once the stack is created, select the `drift-detection-challenge` stack and choose **Resources**. Take a note of the **Physical ID** for `Instance1`, for example `i-1234567890abcdef0`.
    ::::
```

2023-05-15 05:42 UTC, cjhar requested changes
Thanks, still two places where showCopyAction=true needs update on lines 170 and 239
```
:::code{language=shell showLineNumbers=false showCopyAction=false}
```

2023-05-17 10:20 UTC, cjhar submitted a review, later dismissed

2023-05-17 12:32 UTC, rezabekf requested changes
The challenge section is missing Cloud 9 instructions, please update. Thanks.

2023-05-17 12:32 UTC, rezabekf commented on content/intermediate/operations/drift-detection/index.md
> +1. Update the stack with the updated template file. CloudFormation will remove the instance from the stack without terminating it.
Missing Cloud 9 instructions for updating the stack

2023-05-17 12:32 UTC, rezabekf commented on content/intermediate/operations/drift-detection/index.md
> +1. Once the stack operation is complete and the resource is imported, you can run drift detection on the stack to confirm the instance is now in sync with the stack template.
Missing Cloud 9 instructions for updating the stack

2023-05-25 01:13 UTC, cjhar reviewed
Thanks Avinash, only a couple of small issues

2023-05-26 05:05 UTC, cjhar reviewed
Thanks LGTM

2023-05-26 12:29 UTC, rezabekf approved these changes
Tough one...great work!

2023-05-26 12:29 UTC, merged