Cloud9 Support for Stacksets
aws-samples/cfn101-workshop pull request #227
Opened 2023-05-05 17:06 UTC by AvinashSeelam9

## What does this PR do and why?
This PR provides Cloud9 support for StackSets
_Describe in detail what your merge request does and why._
This PR provides Cloud9 support for StackSets
## Issue #, if available

## PR acceptance checklist

This checklist encourages us to confirm any changes have been analyzed to reduce risks in quality, performance, reliability, security, and maintainability.

- [x] Added/Updated documentation if applicable.
- [x] Pre-commit checks passed.
- [x] Lint and Nag checks passed.
- [ ] If releasing a new version, have you bumped the version `make version part=<major|minor|patch>`?

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-05-17 09:55 UTC, cjhar requested changes
Thanks please see review comments and also fix

line 59 8. Select **Submit**.

2023-05-17 09:55 UTC, cjhar commented on content/intermediate/operations/stacksets/index.md
> +    1. The **Status** changes to `PENDING`.
```suggestion
    1. On the **Review** page, review the contents of the page, and choose **Submit**.
    1. The **Status** changes to `PENDING`.
```

2023-05-17 09:55 UTC, cjhar commented on content/intermediate/operations/stacksets/index.md
> +    5. In the popup that appears, confirm you want to delete this stack set by choosing **Delete StackSet**.
```suggestion
    1. In the popup that appears, confirm you want to delete this stack set by choosing **Delete**.
```

2023-05-17 09:55 UTC, cjhar commented on content/intermediate/operations/stacksets/index.md
> +    4. Under **Accounts**, select **Deploy stacks in accounts** under **Deployment locations**.
```suggestion
```

2023-05-17 09:55 UTC, cjhar commented on content/intermediate/operations/stacksets/index.md
> +    7. Follow steps 2 through 6 for the two other stack sets.
```suggestion
    1. Follow steps 2 through 5 for the two other stack sets.
```

2023-05-17 09:55 UTC, cjhar commented on content/intermediate/operations/stacksets/index.md
> +    6. On refresh, your StackSet should no longer be listed.
```suggestion
    1. On refresh, your StackSet should no longer be listed.
```

2023-05-17 09:55 UTC, cjhar commented on content/intermediate/operations/stacksets/index.md
> +    3. Choose **Actions**, and then **Delete StackSet**.
```suggestion
    1. Choose **Actions**, and then **Delete StackSet**.
```

2023-05-17 09:55 UTC, cjhar commented on content/intermediate/operations/stacksets/index.md
> +    2. Select the stack set you wish to delete.
```suggestion
    1. Select the stack set you wish to delete.
```

2023-05-17 10:55 UTC, cjhar submitted a review, later dismissed
LGTM

2023-05-22 09:46 UTC, rezabekf approved these changes
Approved.

2023-05-22 09:46 UTC, merged