Copied manually modification from ja-05-intermediate branch
aws-samples/cfn101-workshop pull request #243
Opened 2023-08-22 11:07 UTC by ttymt

@cmick-aws 
Please review Japanese translation for the intermediate part.

2023-08-25 01:55 UTC, cmick-aws commented
This PR is a follow of #182 where the "templates" sections has been reviewed.

2023-08-25 05:20 UTC, cmick-aws requested changes
@ttymt, I finished the Japanese translation review for the 'operations' section.
Please check the change requests.

2023-08-25 05:20 UTC, cmick-aws commented on content/intermediate/operations/drift-detection/index.ja.md
> +::alert[この `UserData` スクリプトは、インスタンスの初回起動時にのみ実行されます。起動のたびにスクリプトを実行することで [設定を作成する](https://repost.aws/ja/knowledge-center/execute-user-data-ec2) のも良いですが、今回のワークショップではテンプレートの複雑さを低く抑えるため、このテンプレートでは簡単な内容だけ
「実行する**ために**」でしょうか？

2023-08-25 05:20 UTC, cmick-aws commented on content/intermediate/operations/drift-detection/index.ja.md
>  4.ドリフト検出が完了するまでに少し時間がかかります。**ドリフトステータス** フィールドに `Drifted` と表示されるまで、スタック情報ページを更新します。
「4.」の後ろにスペースが必要

2023-08-25 05:20 UTC, cmick-aws commented on content/intermediate/operations/drift-detection/index.ja.md
>  1. `drift-detection-challenge.yaml` テンプレートを更新して、値が `Retain` の `DeeletionPolicy` 属性を `Instance1` リソースに追加し、ファイルを保存します。
「DeeletionPolicy」には「e」は多い。

2023-08-25 05:20 UTC, cmick-aws commented on content/intermediate/operations/drift-detection/index.ja.md
>  3. **削除**を選択し、**スタックの削除**をクリックします。
「**スタックの削除**」は「**削除**」に変わりました。

2023-08-25 05:20 UTC, cmick-aws commented on content/intermediate/operations/drift-detection/index.ja.md
>  ### まとめ
「新しい望ましい状態」には、「望ましい状態」だけでどう？

2023-08-25 05:20 UTC, cmick-aws requested changes
@ttymt, I finished the Japanese translation review for the 'operations' section.
Please check the change requests.

2023-08-25 08:19 UTC, ttymt commented on content/intermediate/operations/update-behaviors-of-stack-resources/index.ja.md
> +前の例を続けてみましょう。インスタンスは現在、[基本モニタリング](https://docs.aws.amazon.com/ja_jp/AWSEC2/latest/UserGuide/using-cloudwatch-new.html)を使用しており、インスタンスのメトリクスデータが 5分間隔で[Amazon CloudWatch](https://aws.amazon.com/jp/cloud
Done

2023-08-25 08:21 UTC, ttymt commented on content/intermediate/operations/update-behaviors-of-stack-resources/index.ja.md
> +ワークロードの要件が変わり、CPUとメモリの要件に合わせて新しい[Amazon EC2](https://aws.amazon.com/jp/ec2/instance-types/)インスタンスタイプが必要だと判断した例を見てみましょう。例えば、`cfn-workshop-update-behaviors-of-stack-resources` スタックで管理するインスタンスのタイプを、`t2.
Done

2023-08-25 08:22 UTC, ttymt commented on content/intermediate/operations/update-behaviors-of-stack-resources/index.ja.md
>  **一時的な中断を伴う更新**
Done

2023-08-25 08:23 UTC, ttymt commented on content/intermediate/operations/update-behaviors-of-stack-resources/index.ja.md
> +::alert[リソースのプロパティ値を変更するときは、必ずドキュメント内の特定のリソースプロパティの[ Update requires](https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance.html#cfn-ec2-instance-imageid)の値
Done

2023-08-25 08:24 UTC, ttymt commented on content/intermediate/operations/update-behaviors-of-stack-resources/index.ja.md
> +ここまで、スタックを使用して Amazon EC2 インスタンスを作成しました。インスタンスの[Amazon Machine Image](https://docs.aws.amazon.com/ja_jp/AWSEC2/latest/UserGuide/AMIs.html) (AMI) には、このラボで最新の `x86-64` Amazon Linux 2 AMI を使用しました。次に、Ama
Done

2023-08-25 08:24 UTC, ttymt commented on content/intermediate/operations/update-behaviors-of-stack-resources/index.ja.md
> +テンプレートに[Amazon Elastic Compute Cloud](https://aws.amazon.com/jp/ec2/)(Amazon EC2) インスタンスを記述することから始めましょう。`update-behaviors-of-stack-resources.yaml` テンプレートの横に表示されている `Paramaters` セクションをコピーして追加します。
Done

2023-08-25 08:25 UTC, ttymt commented on content/intermediate/operations/update-behaviors-of-stack-resources/index.ja.md
> +* お好みのテキストエディタで`update-behaviors-of-stack-resources.yaml` ファイルを開きます。
Done

2023-08-25 08:26 UTC, ttymt commented on content/intermediate/operations/update-behaviors-of-stack-resources/index.ja.md
> +テンプレートに[Amazon Elastic Compute Cloud](https://aws.amazon.com/jp/ec2/)(Amazon EC2) インスタンスを記述することから始めましょう。`update-behaviors-of-stack-resources.yaml` テンプレートの横に表示されている `Paramaters` セクションをコピーして追加します。
Done

2023-08-25 08:27 UTC, ttymt commented on content/intermediate/operations/update-behaviors-of-stack-resources/index.ja.md
> +CloudFormation は、提供された更新されたテンプレートと、以前のバージョンのテンプレートで説明したリソース構成との変更を比較することによってリソースを更新します。変更されていないリソース構成は、更新プロセス中も影響を受けません。それ以外の場合、CloudFormation は次のいずれかの[更新動作](https://docs.aws.amazon.com/ja_jp/AWSClou
Done

2023-08-25 08:27 UTC, ttymt commented on content/intermediate/operations/update-behaviors-of-stack-resources/index.ja.md
> +CloudFormation は、提供された更新されたテンプレートと、以前のバージョンのテンプレートで説明したリソース構成との変更を比較することによってリソースを更新します。変更されていないリソース構成は、更新プロセス中も影響を受けません。それ以外の場合、CloudFormation は次のいずれかの[更新動作](https://docs.aws.amazon.com/ja_jp/AWSClou
Done

2023-08-25 08:28 UTC, ttymt commented on content/intermediate/operations/update-behaviors-of-stack-resources/index.ja.md
> +このラボで使用したテンプレートの `EC2Instance` の `Name` タグキーの `Value` を更新する任務があります。この情報をインスタンスの`Tags`[プロパティ](https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance.html#cfn-
Done

2023-08-25 08:29 UTC, ttymt commented on content/intermediate/operations/update-behaviors-of-stack-resources/index.ja.md
> +::expand[* CloudFormation ドキュメントのどこで、特定のリソースタイプ (この場合は`AWS::EC2:: Instance`[リソース](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance.html))について、特定のリソースプロパティの更新
Done

2023-08-25 08:30 UTC, ttymt commented on content/intermediate/operations/update-behaviors-of-stack-resources/index.ja.md
>  * **削除**を選択した後、**スタックの削除**を押して確定します。
Done

2023-08-25 08:32 UTC, ttymt commented on content/intermediate/operations/understanding-changesets/index.ja.md
> +スタックを[直接](https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-direct.html)更新するか、[変更セット](https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide
Done

2023-08-25 08:33 UTC, ttymt commented on content/intermediate/operations/understanding-changesets/index.ja.md
>      3. **テンプレートの準備**セクションで、**テンプレート準備完了**を選択します。
Done

2023-08-25 08:43 UTC, ttymt commented on content/intermediate/operations/understanding-changesets/index.ja.md
> +`resourceChange` 構造では、リソースの論理 ID、CloudFormation が実行するアクション、リソースの物理 ID、リソースのタイプ、および CloudFormation がリソースを置き換えるかどうかが表示されます。`Details` 構造では、CloudFormation は、[バージョニング設定](https://docs.aws.amazon.com/ja_jp/
Done

2023-08-25 08:44 UTC, ttymt commented on content/intermediate/operations/understanding-changesets/index.ja.md
> +`resourceChange` 構造では、リソースの論理 ID、CloudFormation が実行するアクション、リソースの物理 ID、リソースのタイプ、および CloudFormation がリソースを置き換えるかどうかが表示されます。`Details` 構造では、CloudFormation は、[バージョニング設定](https://docs.aws.amazon.com/ja_jp/
Done

2023-08-25 08:44 UTC, ttymt commented on content/intermediate/operations/understanding-changesets/index.ja.md
> +次に、スタックの更新時に [置換](https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks-update-behaviors.html#update-replacement) を必要とするプロパティ `BucketName` の値を変更します。次に、変更セットを作
Done

2023-08-25 08:45 UTC, ttymt commented on content/intermediate/operations/understanding-changesets/index.ja.md
> +3.新しい一意の[バケット名](https://docs.aws.amazon.com/ja_jp/AmazonS3/latest/userguide/bucketnamingrules.html)を指定して `BucketName` パラメータの値を変更し、前の手順に従って変更セットの作成を完了します。
Done

2023-08-25 08:45 UTC, ttymt commented on content/intermediate/operations/understanding-changesets/index.ja.md
> +前の例とは2つの重要な違いがあることがわかります。まず、`resourceChange` 構造の `replacement` プロパティの値が `True` に設定されています。次に、`detail` 構造の下に `Static` と `Dynamic` の 2 つの評価が表示されます。これらの点について詳しく説明しましょう。
Done

2023-08-25 08:45 UTC, ttymt commented on content/intermediate/operations/understanding-changesets/index.ja.md
> +置換が必要な `BucketName` [プロパティ](https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket.html#aws-properties-s3-bucket-properties) を更新したため、`replacement` の値は `True` です
Done

2023-08-25 08:46 UTC, ttymt commented on content/intermediate/operations/understanding-changesets/index.ja.md
>  `replacement` フィールドの値は、`target` 構造の `requiresRecreation` フィールドで示されます。`requiresRecreation` フィールドが `Never` の場合、`replacement` フィールドは `False` になります。`requiresRecreation` フィールドが `Always` で、`evaluation` フィー
Done

2023-08-25 08:47 UTC, ttymt commented on content/intermediate/operations/understanding-changesets/index.ja.md
> +お好みのテキストエディタで、`code/workspace/understanding-changesets` ディレクトリにある `changeset-challenge.yaml` という名前のテンプレートファイルを開きます。このファイルは、以前に使用した `bucket.yaml` テンプレートの修正版です。`MyS3Bucket` ではなく `News3Bucket` の Amazon
Done

2023-08-25 08:47 UTC, ttymt commented on content/intermediate/operations/understanding-changesets/index.ja.md
> +* CloudFormation は、新しい `MySQsQueue` キューリソースを追加することに加えて、`News3Bucket` 論理 ID を使用して新しいバケットを作成し、`MyS3Bucket` を削除しようとします。新しいリソースの物理 ID は作成されるまで使用できません。**JSON の変更**は次のようになるはずです。
Done

2023-08-25 08:47 UTC, ttymt commented on content/intermediate/operations/understanding-changesets/index.ja.md
> +* CloudFormation は、新しい `MySQsQueue` キューリソースを追加することに加えて、`News3Bucket` 論理 ID を使用して新しいバケットを作成し、`MyS3Bucket` を削除しようとします。新しいリソースの物理 ID は作成されるまで使用できません。**JSON の変更**は次のようになるはずです。
Done

2023-08-25 08:48 UTC, ttymt commented on content/intermediate/operations/understanding-changesets/index.ja.md
>  2. **削除** を選択し、次に**スタックの削除** を選択してスタックと、スタック用に作成した変更セットを削除します。
Done

2023-08-25 08:49 UTC, ttymt commented on content/intermediate/operations/stack-policy-and-prevention-controls/index.ja.md
> +[AWS CloudFormation](https://aws.amazon.com/cloudformation/) を使用してコードでインフラストラクチャを記述する場合、意図しない操作を防ぐためのポリシーを実装するかを選択できます。例えば、[スタックポリシー](https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGu
Done

2023-08-25 08:49 UTC, ttymt commented on content/intermediate/operations/stack-policy-and-prevention-controls/index.ja.md
> +[AWS CloudFormation](https://aws.amazon.com/cloudformation/) を使用してコードでインフラストラクチャを記述する場合、意図しない操作を防ぐためのポリシーを実装するかを選択できます。例えば、[スタックポリシー](https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGu
Done

2023-08-25 08:50 UTC, ttymt commented on content/intermediate/operations/stack-policy-and-prevention-controls/index.ja.md
> +* CloudFormation スタックに [スタックポリシー](https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/protect-stack-resources.html) を設定して、スタックで管理しているリソースに対して実行できる更新アクションを決定する方法を学びます。
Done

2023-08-25 08:50 UTC, ttymt commented on content/intermediate/operations/stack-policy-and-prevention-controls/index.ja.md
> +* [DeletionPolicy](https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/aws-attribute-deletionpolicy.html) 属性を使用して、スタックからリソースを削除するとき、またはスタックを削除するときに、スタックに記述したリソースを保存 (場合によってはバックアップ) す
Done

2023-08-25 08:51 UTC, ttymt commented on content/intermediate/operations/stack-policy-and-prevention-controls/index.ja.md
>  開始するには、次に示す手順に従ってください。
Done

2023-08-25 08:52 UTC, ttymt commented on content/intermediate/operations/stack-policy-and-prevention-controls/index.ja.md
Done

2023-08-25 08:53 UTC, ttymt commented on content/intermediate/operations/stack-policy-and-prevention-controls/index.ja.md
> +[DeletionPolicy](https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/aws-attribute-deletionpolicy.html) は、スタックからリソースを削除する場合やスタック自体を削除する場合に、スタック内のリソースを保存 (場合によってはバックアップ) するように設定する Clo
Done

2023-08-25 08:53 UTC, ttymt commented on content/intermediate/operations/stack-policy-and-prevention-controls/index.ja.md
>  このラボでは、まず Amazon SNS トピックリソースを含む CloudFormation スタックを作成し、`DeletionPolicy` 属性値を `Retain` に設定してリソースを保存します。次に、スタックを削除し、リソースがまだ存在するかどうかを確認します。
Done

2023-08-25 08:54 UTC, ttymt commented on content/intermediate/operations/stack-policy-and-prevention-controls/index.ja.md
>  1. [Amazon SNS コンソール](https://console.aws.amazon.com/sns/) に移動し、**トピック** を選択します。
Done

2023-08-25 08:54 UTC, ttymt commented on content/intermediate/operations/stack-policy-and-prevention-controls/index.ja.md
> +おめでとうございます！ これで、リソースに `DeletionPolicy` リソース属性を定義して、スタックの削除時にその属性を保持する方法を学習しました。詳しい情報については、[`DeletionPolicy` 属性](https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/aws-attribute-dele
Done

2023-08-25 08:55 UTC, ttymt commented on content/intermediate/operations/stack-policy-and-prevention-controls/index.ja.md
>  {
Done

2023-08-25 08:56 UTC, ttymt commented on content/intermediate/operations/resource-importing/index.ja.md
> +[スタック間でリソースを移動する](https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/refactor-stacks.html) 場合は、インポート機能を使用することもできます。これにより、スタックとリソースを [ライフサイクルと所有権](https://docs.aws.amazon.com/ja_jp/A
Done

2023-08-25 08:57 UTC, ttymt commented on content/intermediate/operations/resource-importing/index.ja.md
>  ### 取り上げるトピック
Done

2023-08-25 08:58 UTC, ttymt commented on content/intermediate/operations/resource-importing/index.ja.md
> +::alert[インポート操作を成功させるには、インポートするすべてのリソースにテンプレートに [DeletionPolicy](https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/aws-attribute-deletionpolicy.html) 属性が設定されている必要があります。詳しい情報については、[
Done

2023-08-25 09:00 UTC, ttymt commented on content/intermediate/operations/resource-importing/index.ja.md
>  3. **概要をインポート**を読み、**次へ**をクリックします。
Done

2023-08-25 09:01 UTC, ttymt commented on content/intermediate/operations/resource-importing/index.ja.md
>  8. **概要をインポート**を読み、**次へ**をクリックします。
Done

2023-08-25 09:02 UTC, ttymt commented on content/intermediate/operations/drift-detection/index.ja.md
> +::alert[この `UserData` スクリプトは、インスタンスの初回起動時にのみ実行されます。起動のたびにスクリプトを実行することで [設定を作成する](https://repost.aws/ja/knowledge-center/execute-user-data-ec2) のも良いですが、今回のワークショップではテンプレートの複雑さを低く抑えるため、このテンプレートでは簡単な内容だけ
Done

2023-08-25 09:02 UTC, ttymt commented on content/intermediate/operations/drift-detection/index.ja.md
>  4.ドリフト検出が完了するまでに少し時間がかかります。**ドリフトステータス** フィールドに `Drifted` と表示されるまで、スタック情報ページを更新します。
Done

2023-08-25 09:03 UTC, ttymt commented on content/intermediate/operations/drift-detection/index.ja.md
>  1. `drift-detection-challenge.yaml` テンプレートを更新して、値が `Retain` の `DeeletionPolicy` 属性を `Instance1` リソースに追加し、ファイルを保存します。
Done

2023-08-25 09:03 UTC, ttymt commented on content/intermediate/operations/drift-detection/index.ja.md
>  3. **削除**を選択し、**スタックの削除**をクリックします。
Done

2023-08-25 09:05 UTC, ttymt commented on content/intermediate/operations/drift-detection/index.ja.md
>  ### まとめ
Done

2023-08-28 06:13 UTC, ttymt commented on content/intermediate/operations/resource-importing/index.ja.md
>  EC2 インスタンスと Amazon S3 バケットを説明するサンプルテンプレートから始めましょう。
Done

2023-08-28 06:15 UTC, ttymt commented on content/intermediate/operations/resource-importing/index.ja.md
>  7. **スタックの名前**を入力します。例えば、`resource-import-challenge` と指定します。`InstanceType` には `t2.nano` を指定します。[**次へ**]をクリックします。
Done

2023-08-28 06:17 UTC, ttymt commented on content/intermediate/operations/resource-importing/index.ja.md
>  3. スタックを更新し、インスタンスの `DeletionPolicy` 属性が `Retain` に設定されたら、`Parameters` セクションにあるインスタンスリソース定義と関連パラメータをテンプレートから削除します。今回の例では、書くべきパラメーターが特に存在しないため、`Parameters` セクション自体を削除します。具体的には、`resource-import-challen
Done

2023-08-28 06:22 UTC, ttymt commented on content/intermediate/operations/resource-importing/index.ja.md
>  7. **概要をインポート**を読み、**次へ**を選択してください。
Done

2023-08-28 06:24 UTC, ttymt commented on content/intermediate/operations/drift-detection/index.ja.md
> +[AWS CloudFormation](https://aws.amazon.com/jp/cloudformation/) を使用してリソースをプロビジョニングすることを選択した場合、必要に応じて CloudFormation を使用してリソースの設定を長期にわたって維持することになります。その後、そのようなリソースを CloudFormation の範囲外で管理することを選択した場合 (例
Done

2023-08-28 06:33 UTC, ttymt commented on content/intermediate/operations/drift-detection/index.ja.md
> +CloudFormation は[ドリフト検出](https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/using-cfn-stack-drift.html) を提供しています。これは、リソースの現在の構成と、リソースの作成または更新に使用したテンプレートで宣言した構成との違いに関する情報を提供します。ドリフト検
Done

2023-08-28 06:33 UTC, ttymt commented on content/intermediate/operations/drift-detection/index.ja.md
> +CloudFormation は[ドリフト検出](https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/using-cfn-stack-drift.html) を提供しています。これは、リソースの現在の構成と、リソースの作成または更新に使用したテンプレートで宣言した構成との違いに関する情報を提供します。ドリフト検
Done

2023-08-28 06:35 UTC, ttymt commented on content/intermediate/operations/drift-detection/index.ja.md
>  3. テンプレート内のリソース例をよく理解してください。
よく確認した上で、実施してください。でDone

2023-08-28 06:37 UTC, ttymt commented on content/intermediate/operations/drift-detection/index.ja.md
>  2. `Queue1` の `MessageRetentionPeriod` を、前のステップで見たドリフト詳細ページの**現在の値** 列に表示された値と一致するように変更します。テンプレートの `MessageRetentionPeriod` の値を `172800` に設定します。これは `2` 日の秒数です。
Done

2023-08-28 09:31 UTC, cmick-aws commented
Please fix 1 last point.

2023-08-28 09:32 UTC, cmick-aws reviewed
Please fix 1 last point.

2023-08-28 12:21 UTC, cmick-aws approved these changes
Review is complete.
@ttymt , Please squash-merge to main.ja branch.

2023-08-28 12:25 UTC, merged