Translation of 'intermediate' section
aws-samples/cfn101-workshop pull request #244
Opened 2023-08-23 04:44 UTC by ttymt

## What does this PR do and why?

_Describe in detail what your merge request does and why._

## Issue #, if available

## PR acceptance checklist

This checklist encourages us to confirm any changes have been analyzed to reduce risks in quality, performance, reliability, security, and maintainability.

- [ ] Added/Updated documentation if applicable.
- [ ] Pre-commit checks passed.
- [ ] Lint and Nag checks passed.
- [ ] If releasing a new version, have you bumped the version `make version part=<major|minor|patch>`?

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-08-25 09:31 UTC, cmick-aws requested changes
@ttymt , I finished the review. Please check change requests.

2023-08-25 09:31 UTC, cmick-aws commented on content/advanced/resource-types/example-in_Python/index.ja.md
> +おめでとうございます! Python でのサンプルリソースタイプ実装を順を追って説明し、リソースタイプを作成する際に留意すべき重要な概念、期待される事項、目的を学びました。
「サンプルリソースタイプ実装を順を追って説明し」
は
「サンプルリソースタイプの実装を一通り実施し」
でどうですか？

2023-08-28 14:22 UTC, ttymt commented on content/advanced/index.ja.md
> +title: "上級"
Done

2023-08-28 14:23 UTC, ttymt commented on content/advanced/index.ja.md
> +ワークショップの**上級**パートへようこそ。
Done

2023-08-28 14:23 UTC, ttymt commented on content/advanced/index.ja.md
> +このパートでは、開発した拡張機能を使用して [AWS CloudFormation](https://aws.amazon.com/jp/cloudformation/) の作成、プロビジョニング、管理に関する機能を拡張する方法に焦点を当てます。
Done

2023-08-28 14:24 UTC, ttymt commented on content/advanced/modules/index.ja.md
> +::alert[モジュールの使用には追加料金はありません。お支払いいただくのは、モジュールがスタック内で解決するリソース分のみです。]{type="info"}
Done

2023-08-28 14:26 UTC, ttymt commented on content/advanced/modules/create-example/index.ja.md
> +このラボでは、AWS アカウントで指定した AWS リージョンの AWS CloudFormation レジストリに、サンプルの CloudFormation モジュールをプライベート拡張で登録する手順を実施します。
Done

2023-08-28 14:28 UTC, ttymt commented on content/advanced/modules/create-example/index.ja.md
> +* [CloudFormation コマンドラインインターフェイス (CLI)](https://docs.aws.amazon.com/ja_jp/cloudformation-cli/latest/userguide/what-is-cloudformation-cli.html) を使用して新しいプロジェクトを作成し、そのモジュールをプライベート拡張として、AWS アカウント内で指定した
Done

2023-08-28 14:28 UTC, ttymt commented on content/advanced/modules/create-example/index.ja.md
> +CloudFormation モジュールは、このワークショップで既に作成しているものと同様に、標準のCloudFormationテンプレートを使用して作成されます。ただし、モジュールで使用できるテンプレートファイルは 1 つだけで、ネストされたスタックはサポートされていません。詳細については、[モジュール構造](https://docs.aws.amazon.com/ja_jp/cloudfor
Done

2023-08-28 14:29 UTC, ttymt commented on content/advanced/modules/create-example/index.ja.md
> +テキストエディターでこのファイルを開き、以下の CloudFormatoin YAML コードを貼り付けます。
Done

2023-08-28 14:30 UTC, ttymt commented on content/advanced/modules/create-example/index.ja.md
> +  Type: String
Done

2023-08-28 14:32 UTC, ttymt commented on content/advanced/modules/consume-example/index.ja.md
> +AWS アカウントで指定した AWS リージョンのプライベートレジストリに、新しい CloudFormation モジュールを作成して登録しました。つまり、モジュールを CloudFormation テンプレートで他のAWS リソースと同じように使用できるようになりました。
Done

2023-08-28 14:32 UTC, ttymt commented on content/advanced/modules/consume-example/index.ja.md
> +AWS アカウントで指定した AWS リージョンのプライベートレジストリに、新しい CloudFormation モジュールを作成して登録しました。つまり、モジュールを CloudFormation テンプレートで他のAWS リソースと同じように使用できるようになりました。
Done

2023-08-28 14:36 UTC, ttymt commented on content/advanced/resource-types/index.ja.md
> +このパートでは、開発したリソースタイプを使用して [AWS CloudFormation](https://aws.amazon.com/jp/cloudformation/) の作成、プロビジョニング、管理に関する機能を拡張する方法に焦点を当てます。
Done

2023-08-28 14:37 UTC, ttymt commented on content/advanced/resource-types/index.ja.md
> +2.  リソースタイプに合わせたテストの開発と実行を開始します。
Done

2023-08-28 14:37 UTC, ttymt commented on content/advanced/resource-types/index.ja.md
> +3.  準備ができたら、リソースタイプを [AWS CloudFormation レジストリ](https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/registry.html)に送信します。
Done

2023-08-28 14:39 UTC, ttymt commented on content/advanced/resource-types/prerequisites/index.ja.md
> +次のセクションに進む前に、以下の前提条件をマシンにインストールすることを選択してください。
Done

2023-08-28 14:41 UTC, ttymt commented on content/advanced/resource-types/prerequisites/index.ja.md
> +* 次に示すリンクにあるご使用のオペレーティングシステム用のメモに従って [AWS SAM CLI](https://docs.aws.amazon.com/ja_jp/serverless-application-model/latest/developerguide/serverless-sam-reference.html#serverless-sam-cli) をインストールします。SA
Done

2023-08-28 14:45 UTC, ttymt commented on content/advanced/resource-types/prerequisites/index.ja.md
> +* [Python での実装例](example-in_python)ラボでは、サンプルアプリケーションのユニットテストを実行するために必要な以下のパッケージをインストールします。
Done

2023-08-28 14:46 UTC, ttymt commented on content/advanced/resource-types/example-in_Python/index.ja.md
> +このモジュールでは、Python で記述されたサンプルプライベート拡張を AWS アカウントの AWS CloudFormation レジストリに登録する手順を実施します。また、リソースタイプのソースコード実装ロジックの例を確認して、リソースタイプ開発ワークフローの主要な概念を理解します。
Done

2023-08-28 14:48 UTC, ttymt commented on content/advanced/resource-types/example-in_Python/index.ja.md
> +* `inputs/`: リソースタイプ入力プロパティのキー/値データを含むファイルが含まれています。リソースタイプ作成者は、コントラクトテストで使用する入力情報を指定します。*これらのファイルに機密情報を追加しないでください。*詳細については、[Specifying input data for use in contract tests](https://docs.aws.amazon.co
Done

2023-08-28 14:49 UTC, ttymt commented on content/advanced/resource-types/example-in_Python/index.ja.md
> +    - `handlers.py`: リソースタイプ開発者が CRUDL 実装ロジックのコードを追加する場所です。任意のテキストエディタで `src/handlers.py` ファイルを開き、`create_handler`、`update_handler`、`delete_handler`、`read_handler`、`list_handler` 関数で示されているように**ハンドラーの
Done

2023-08-28 14:50 UTC, ttymt commented on content/advanced/resource-types/example-in_Python/index.ja.md
> +* インポートするキーペアの `KeyName` (*Required: Yes* Requrirementのドキュメントに記載)
Done

2023-08-28 14:50 UTC, ttymt commented on content/advanced/resource-types/example-in_Python/index.ja.md
> +次に、*レスポンス要素*を見てみましょう。リソースを作成すると、`keyFingerprint`を含む他の要素とともに `keyPairId` が返されます。[DeleteKeyPair](https://docs.aws.amazon.com/ja_jp/AWSEC2/latest/APIReference/API_DeleteKeyPair.html) アクションは、`KeyName` を含
Done

2023-08-28 14:51 UTC, ttymt commented on content/advanced/resource-types/example-in_Python/index.ja.md
> +次に、*レスポンス要素*を見てみましょう。リソースを作成すると、`keyFingerprint`を含む他の要素とともに `keyPairId` が返されます。[DeleteKeyPair](https://docs.aws.amazon.com/ja_jp/AWSEC2/latest/APIReference/API_DeleteKeyPair.html) アクションは、`KeyName` を含
Done

2023-08-28 14:51 UTC, ttymt commented on content/advanced/resource-types/example-in_Python/index.ja.md
> +他の 2 つのハンドラーには追加のプロパティが必要です。*read* (リソースの現在の状態情報が必要な場合に CloudFormation がスタック更新時に呼び出す) と *list* (特定のタイプの複数のリソースについて概要情報が必要な場合に呼び出される) です。この例では、`keySet` や `KeyType` などの関連するプロパティを探すために、[`DescribeKeyPair
Done

2023-08-28 15:15 UTC, ttymt commented on content/advanced/resource-types/example-in_Python/index.ja.md
> +* モデルのプロパティと値の制約については、`properties` セクションで説明しています。
Done

2023-08-28 15:18 UTC, ttymt commented on content/advanced/resource-types/example-in_Python/index.ja.md
> +* `PublicKeyMaterial` は `writeOnlyProperties` で指定されます。機密データ (パスワードなど) を含む値を記述するときには `writeOnlyProperties` がよく使われます。これらの値は *list* や *read* のリクエストでは返されません。`AWSSamples::EC2::ImportKeyPair` の例では、*list* や
Done

2023-08-28 15:19 UTC, ttymt commented on content/advanced/resource-types/example-in_Python/index.ja.md
> +    * 特定のサービス固有の API (*create* ハンドラーの `ImportKeyPair`、`DeleteKeyPair` *delete* ハンドラーのなど) を呼び出します。
Done

2023-08-28 15:20 UTC, ttymt commented on content/advanced/resource-types/example-in_Python/index.ja.md
> +ソフトウェア開発のベストプラクティスの一環として、*unit tests* を作成して、コードが期待どおりに動作するという確信を高めます。[ノート](https://github.com/aws-cloudformation/aws-cloudformation-samples/tree/main/resource-types/awssamples-ec2-importkeypair/pytho
Done

2023-08-28 15:20 UTC, ttymt commented on content/advanced/resource-types/example-in_Python/index.ja.md
> +このラボの以降のステップでは、`AWSSamples::EC2::ImportKeyPair` サンプルリソースタイプをプライベート拡張としてローカルでテストし、アカウントの CloudFormation レジストリに送信します。
Done

2023-08-28 15:22 UTC, ttymt commented on content/advanced/resource-types/example-in_Python/index.ja.md
> +CloudFormation CLI を使用して CloudFormation アカウントのレジストリにリソースを送信してみましょう (この例では、AWS リージョンに `us-east-1` を使用しています)。
Done

2023-08-28 15:22 UTC, ttymt commented on content/advanced/resource-types/example-in_Python/index.ja.md
> +* 作成した `example-key-pair-stack` CloudFormation スタックの `Outputs` セクションから: `KeyPairId` の値を使用し、それを JSON ファイルの構造内の `desiredResourceState` キーの下に作成した新しい `KeyPairId` キーに渡します。
Done

2023-08-28 15:23 UTC, ttymt commented on content/advanced/resource-types/example-in_Python/index.ja.md
> +おめでとうございます! Python でのサンプルリソースタイプ実装を順を追って説明し、リソースタイプを作成する際に留意すべき重要な概念、期待される事項、目的を学びました。
Done

2023-08-29 02:50 UTC, cmick-aws requested changes
@ttymt , only 1 point to fix. Please check.
Also, please include localized screenshots.

2023-08-29 02:50 UTC, cmick-aws commented on content/advanced/index.ja.md
> +このパートでは、開発した拡張機能を使用して [AWS CloudFormation](https://aws.amazon.com/jp/cloudformation/) の作成、プロビジョニング、管理に関する機能を拡張する方法に焦点を当てます。
後続のページでは、「パート」が「編」に置き換えられたので、こちらも合わせてみたらいかがでしょうか？

2023-08-29 02:50 UTC, cmick-aws commented on content/advanced/resource-types/example-in_Python/index.ja.md
> +::alert[パブリックリソースタイプを公開するにはコントラクトテストに合格する必要があり、プライベートリソースタイプを送信した場合は実行されません。ただし、ベスト・プラクティスの一環として、開発プロセスの非常に早い段階でコントラクト・テストの仕様を順守するようにしてください。]{type="info"}
了解！

2023-08-30 09:33 UTC, cmick-aws reviewed
画像置き換え完了

2023-08-30 09:33 UTC, cmick-aws commented on content/advanced/modules/consume-example/index.ja.md
> +![stack-resources](/static/advanced/modules/StackResources.png)
画像を置き換えました。

2023-08-30 09:33 UTC, cmick-aws commented on content/advanced/modules/consume-example/index.ja.md
> +![stack-template](/static/advanced/modules/StackTemplate.png)
画像を置き換えました。

2023-08-30 09:33 UTC, cmick-aws commented on content/advanced/modules/create-example/index.ja.md
> +![activated-extensions](/static/advanced/modules/ActivatedExtensions.png)
画像を置き換えました。

2023-08-30 09:34 UTC, cmick-aws commented on content/advanced/index.ja.md
> +このパートでは、開発した拡張機能を使用して [AWS CloudFormation](https://aws.amazon.com/jp/cloudformation/) の作成、プロビジョニング、管理に関する機能を拡張する方法に焦点を当てます。
修正しました。

2023-08-30 09:38 UTC, cmick-aws approved these changes
@ttymt , I finished my review.
Please squash-merge when you are ready.

2023-08-30 16:04 UTC, merged