Change wording form layered to cross-stack references
aws-samples/cfn101-workshop pull request #253
Opened 2023-11-14 18:34 UTC by rezabekf

## What does this PR do and why?

This PR changes the wording to be consistent with AWS  terminology.

## Issue #, if available

## PR acceptance checklist

This checklist encourages us to confirm any changes have been analyzed to reduce risks in quality, performance, reliability, security, and maintainability.

- [ ] Added/Updated documentation if applicable.
- [ ] Pre-commit checks passed.
- [ ] Lint and Nag checks passed.
- [ ] If releasing a new version, have you bumped the version `make version part=<major|minor|patch>`?

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-11-14 20:53 UTC, mrinaudo-aws requested changes
Thank you @rezabekf - please fix the typo to which I am pointing in my suggestion, otherwise LGTM.

2023-11-14 20:53 UTC, mrinaudo-aws commented on content/intermediate/templates/cross-stacks/index.md
> +--stack-name cfn-workshop-cross-stackss-vpc \
```suggestion
--stack-name cfn-workshop-cross-stacks-vpc \
```

2023-11-15 11:55 UTC, rezabekf commented
@cmick-aws, could you please review Japanese translation for this change? I have updated static files links, however the text will need to be done by you or your team. Thank you!

2023-11-21 14:13 UTC, mrinaudo-aws approved these changes
LGTM

2023-11-21 14:15 UTC, merged

2023-11-21 15:00 UTC, cmick-aws commented
@rezabekf , Please let me apply corresponding changes to the other PRs.